/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
)

// checks if the MentalModelTrigger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelTrigger{}

// MentalModelTrigger Trigger settings for a mental model.
type MentalModelTrigger struct {
	// If true, refresh this mental model after observations consolidation (real-time mode)
	RefreshAfterConsolidation *bool `json:"refresh_after_consolidation,omitempty"`
	FactTypes []string `json:"fact_types,omitempty"`
	// If true, exclude all mental models from the reflect loop (skip search_mental_models tool).
	ExcludeMentalModels *bool `json:"exclude_mental_models,omitempty"`
	ExcludeMentalModelIds []string `json:"exclude_mental_model_ids,omitempty"`
	TagsMatch NullableString `json:"tags_match,omitempty"`
	TagGroups []MentalModelTriggerTagGroupsInner `json:"tag_groups,omitempty"`
}

// NewMentalModelTrigger instantiates a new MentalModelTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelTrigger() *MentalModelTrigger {
	this := MentalModelTrigger{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	var excludeMentalModels bool = false
	this.ExcludeMentalModels = &excludeMentalModels
	return &this
}

// NewMentalModelTriggerWithDefaults instantiates a new MentalModelTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelTriggerWithDefaults() *MentalModelTrigger {
	this := MentalModelTrigger{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	var excludeMentalModels bool = false
	this.ExcludeMentalModels = &excludeMentalModels
	return &this
}

// GetRefreshAfterConsolidation returns the RefreshAfterConsolidation field value if set, zero value otherwise.
func (o *MentalModelTrigger) GetRefreshAfterConsolidation() bool {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		var ret bool
		return ret
	}
	return *o.RefreshAfterConsolidation
}

// GetRefreshAfterConsolidationOk returns a tuple with the RefreshAfterConsolidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTrigger) GetRefreshAfterConsolidationOk() (*bool, bool) {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		return nil, false
	}
	return o.RefreshAfterConsolidation, true
}

// HasRefreshAfterConsolidation returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasRefreshAfterConsolidation() bool {
	if o != nil && !IsNil(o.RefreshAfterConsolidation) {
		return true
	}

	return false
}

// SetRefreshAfterConsolidation gets a reference to the given bool and assigns it to the RefreshAfterConsolidation field.
func (o *MentalModelTrigger) SetRefreshAfterConsolidation(v bool) {
	o.RefreshAfterConsolidation = &v
}

// GetFactTypes returns the FactTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTrigger) GetFactTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FactTypes
}

// GetFactTypesOk returns a tuple with the FactTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTrigger) GetFactTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.FactTypes) {
		return nil, false
	}
	return o.FactTypes, true
}

// HasFactTypes returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasFactTypes() bool {
	if o != nil && !IsNil(o.FactTypes) {
		return true
	}

	return false
}

// SetFactTypes gets a reference to the given []string and assigns it to the FactTypes field.
func (o *MentalModelTrigger) SetFactTypes(v []string) {
	o.FactTypes = v
}

// GetExcludeMentalModels returns the ExcludeMentalModels field value if set, zero value otherwise.
func (o *MentalModelTrigger) GetExcludeMentalModels() bool {
	if o == nil || IsNil(o.ExcludeMentalModels) {
		var ret bool
		return ret
	}
	return *o.ExcludeMentalModels
}

// GetExcludeMentalModelsOk returns a tuple with the ExcludeMentalModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTrigger) GetExcludeMentalModelsOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeMentalModels) {
		return nil, false
	}
	return o.ExcludeMentalModels, true
}

// HasExcludeMentalModels returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasExcludeMentalModels() bool {
	if o != nil && !IsNil(o.ExcludeMentalModels) {
		return true
	}

	return false
}

// SetExcludeMentalModels gets a reference to the given bool and assigns it to the ExcludeMentalModels field.
func (o *MentalModelTrigger) SetExcludeMentalModels(v bool) {
	o.ExcludeMentalModels = &v
}

// GetExcludeMentalModelIds returns the ExcludeMentalModelIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTrigger) GetExcludeMentalModelIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeMentalModelIds
}

// GetExcludeMentalModelIdsOk returns a tuple with the ExcludeMentalModelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTrigger) GetExcludeMentalModelIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeMentalModelIds) {
		return nil, false
	}
	return o.ExcludeMentalModelIds, true
}

// HasExcludeMentalModelIds returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasExcludeMentalModelIds() bool {
	if o != nil && !IsNil(o.ExcludeMentalModelIds) {
		return true
	}

	return false
}

// SetExcludeMentalModelIds gets a reference to the given []string and assigns it to the ExcludeMentalModelIds field.
func (o *MentalModelTrigger) SetExcludeMentalModelIds(v []string) {
	o.ExcludeMentalModelIds = v
}

// GetTagsMatch returns the TagsMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTrigger) GetTagsMatch() string {
	if o == nil || IsNil(o.TagsMatch.Get()) {
		var ret string
		return ret
	}
	return *o.TagsMatch.Get()
}

// GetTagsMatchOk returns a tuple with the TagsMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTrigger) GetTagsMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagsMatch.Get(), o.TagsMatch.IsSet()
}

// HasTagsMatch returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasTagsMatch() bool {
	if o != nil && o.TagsMatch.IsSet() {
		return true
	}

	return false
}

// SetTagsMatch gets a reference to the given NullableString and assigns it to the TagsMatch field.
func (o *MentalModelTrigger) SetTagsMatch(v string) {
	o.TagsMatch.Set(&v)
}
// SetTagsMatchNil sets the value for TagsMatch to be an explicit nil
func (o *MentalModelTrigger) SetTagsMatchNil() {
	o.TagsMatch.Set(nil)
}

// UnsetTagsMatch ensures that no value is present for TagsMatch, not even an explicit nil
func (o *MentalModelTrigger) UnsetTagsMatch() {
	o.TagsMatch.Unset()
}

// GetTagGroups returns the TagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTrigger) GetTagGroups() []MentalModelTriggerTagGroupsInner {
	if o == nil {
		var ret []MentalModelTriggerTagGroupsInner
		return ret
	}
	return o.TagGroups
}

// GetTagGroupsOk returns a tuple with the TagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTrigger) GetTagGroupsOk() ([]MentalModelTriggerTagGroupsInner, bool) {
	if o == nil || IsNil(o.TagGroups) {
		return nil, false
	}
	return o.TagGroups, true
}

// HasTagGroups returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasTagGroups() bool {
	if o != nil && !IsNil(o.TagGroups) {
		return true
	}

	return false
}

// SetTagGroups gets a reference to the given []MentalModelTriggerTagGroupsInner and assigns it to the TagGroups field.
func (o *MentalModelTrigger) SetTagGroups(v []MentalModelTriggerTagGroupsInner) {
	o.TagGroups = v
}

func (o MentalModelTrigger) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelTrigger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshAfterConsolidation) {
		toSerialize["refresh_after_consolidation"] = o.RefreshAfterConsolidation
	}
	if o.FactTypes != nil {
		toSerialize["fact_types"] = o.FactTypes
	}
	if !IsNil(o.ExcludeMentalModels) {
		toSerialize["exclude_mental_models"] = o.ExcludeMentalModels
	}
	if o.ExcludeMentalModelIds != nil {
		toSerialize["exclude_mental_model_ids"] = o.ExcludeMentalModelIds
	}
	if o.TagsMatch.IsSet() {
		toSerialize["tags_match"] = o.TagsMatch.Get()
	}
	if o.TagGroups != nil {
		toSerialize["tag_groups"] = o.TagGroups
	}
	return toSerialize, nil
}

type NullableMentalModelTrigger struct {
	value *MentalModelTrigger
	isSet bool
}

func (v NullableMentalModelTrigger) Get() *MentalModelTrigger {
	return v.value
}

func (v *NullableMentalModelTrigger) Set(val *MentalModelTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelTrigger(val *MentalModelTrigger) *NullableMentalModelTrigger {
	return &NullableMentalModelTrigger{value: val, isSet: true}
}

func (v NullableMentalModelTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


