/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
)

// checks if the UpdateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTemplateRequest{}

// UpdateTemplateRequest Request to update an existing template. All fields optional.  Note: cross-field validation (e.g. custom mode requires custom instructions) cannot be fully checked here because this is a partial update. The endpoint must merge with the existing record and validate the final state.
type UpdateTemplateRequest struct {
	Description *Description `json:"description,omitempty"`
	Author *Author `json:"author,omitempty"`
	Tags *Tags `json:"tags,omitempty"`
	MinHindclawVersion *MinHindclawVersion `json:"min_hindclaw_version,omitempty"`
	MinHindsightVersion NullableMinHindsightVersion `json:"min_hindsight_version,omitempty"`
	RetainMission *RetainMission `json:"retain_mission,omitempty"`
	ReflectMission *ReflectMission `json:"reflect_mission,omitempty"`
	ObservationsMission NullableObservationsMission `json:"observations_mission,omitempty"`
	RetainExtractionMode *RetainExtractionMode `json:"retain_extraction_mode,omitempty"`
	RetainCustomInstructions NullableRetainCustomInstructions `json:"retain_custom_instructions,omitempty"`
	RetainChunkSize *RetainChunkSize `json:"retain_chunk_size,omitempty"`
	RetainDefaultStrategy NullableRetainDefaultStrategy `json:"retain_default_strategy,omitempty"`
	RetainStrategies *RetainStrategies `json:"retain_strategies,omitempty"`
	EntityLabels *EntityLabels `json:"entity_labels,omitempty"`
	EntitiesAllowFreeForm *EntitiesAllowFreeForm `json:"entities_allow_free_form,omitempty"`
	EnableObservations *EnableObservations `json:"enable_observations,omitempty"`
	ConsolidationLlmBatchSize *ConsolidationLlmBatchSize `json:"consolidation_llm_batch_size,omitempty"`
	ConsolidationSourceFactsMaxTokens NullableConsolidationSourceFactsMaxTokens `json:"consolidation_source_facts_max_tokens,omitempty"`
	ConsolidationSourceFactsMaxTokensPerObservation NullableConsolidationSourceFactsMaxTokensPerObservation `json:"consolidation_source_facts_max_tokens_per_observation,omitempty"`
	DispositionSkepticism *DispositionSkepticism `json:"disposition_skepticism,omitempty"`
	DispositionLiteralism *DispositionLiteralism `json:"disposition_literalism,omitempty"`
	DispositionEmpathy *DispositionEmpathy `json:"disposition_empathy,omitempty"`
	DirectiveSeeds *DirectiveSeeds `json:"directive_seeds,omitempty"`
	MentalModelSeeds *MentalModelSeeds `json:"mental_model_seeds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateTemplateRequest UpdateTemplateRequest

// NewUpdateTemplateRequest instantiates a new UpdateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTemplateRequest() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// NewUpdateTemplateRequestWithDefaults instantiates a new UpdateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTemplateRequestWithDefaults() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetDescription() Description {
	if o == nil || IsNil(o.Description) {
		var ret Description
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetDescriptionOk() (*Description, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given Description and assigns it to the Description field.
func (o *UpdateTemplateRequest) SetDescription(v Description) {
	o.Description = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetAuthor() Author {
	if o == nil || IsNil(o.Author) {
		var ret Author
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetAuthorOk() (*Author, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given Author and assigns it to the Author field.
func (o *UpdateTemplateRequest) SetAuthor(v Author) {
	o.Author = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetTags() Tags {
	if o == nil || IsNil(o.Tags) {
		var ret Tags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetTagsOk() (*Tags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given Tags and assigns it to the Tags field.
func (o *UpdateTemplateRequest) SetTags(v Tags) {
	o.Tags = &v
}

// GetMinHindclawVersion returns the MinHindclawVersion field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetMinHindclawVersion() MinHindclawVersion {
	if o == nil || IsNil(o.MinHindclawVersion) {
		var ret MinHindclawVersion
		return ret
	}
	return *o.MinHindclawVersion
}

// GetMinHindclawVersionOk returns a tuple with the MinHindclawVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetMinHindclawVersionOk() (*MinHindclawVersion, bool) {
	if o == nil || IsNil(o.MinHindclawVersion) {
		return nil, false
	}
	return o.MinHindclawVersion, true
}

// HasMinHindclawVersion returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasMinHindclawVersion() bool {
	if o != nil && !IsNil(o.MinHindclawVersion) {
		return true
	}

	return false
}

// SetMinHindclawVersion gets a reference to the given MinHindclawVersion and assigns it to the MinHindclawVersion field.
func (o *UpdateTemplateRequest) SetMinHindclawVersion(v MinHindclawVersion) {
	o.MinHindclawVersion = &v
}

// GetMinHindsightVersion returns the MinHindsightVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetMinHindsightVersion() MinHindsightVersion {
	if o == nil || IsNil(o.MinHindsightVersion.Get()) {
		var ret MinHindsightVersion
		return ret
	}
	return *o.MinHindsightVersion.Get()
}

// GetMinHindsightVersionOk returns a tuple with the MinHindsightVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetMinHindsightVersionOk() (*MinHindsightVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinHindsightVersion.Get(), o.MinHindsightVersion.IsSet()
}

// HasMinHindsightVersion returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasMinHindsightVersion() bool {
	if o != nil && o.MinHindsightVersion.IsSet() {
		return true
	}

	return false
}

// SetMinHindsightVersion gets a reference to the given NullableMinHindsightVersion and assigns it to the MinHindsightVersion field.
func (o *UpdateTemplateRequest) SetMinHindsightVersion(v MinHindsightVersion) {
	o.MinHindsightVersion.Set(&v)
}
// SetMinHindsightVersionNil sets the value for MinHindsightVersion to be an explicit nil
func (o *UpdateTemplateRequest) SetMinHindsightVersionNil() {
	o.MinHindsightVersion.Set(nil)
}

// UnsetMinHindsightVersion ensures that no value is present for MinHindsightVersion, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetMinHindsightVersion() {
	o.MinHindsightVersion.Unset()
}

// GetRetainMission returns the RetainMission field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetRetainMission() RetainMission {
	if o == nil || IsNil(o.RetainMission) {
		var ret RetainMission
		return ret
	}
	return *o.RetainMission
}

// GetRetainMissionOk returns a tuple with the RetainMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetRetainMissionOk() (*RetainMission, bool) {
	if o == nil || IsNil(o.RetainMission) {
		return nil, false
	}
	return o.RetainMission, true
}

// HasRetainMission returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainMission() bool {
	if o != nil && !IsNil(o.RetainMission) {
		return true
	}

	return false
}

// SetRetainMission gets a reference to the given RetainMission and assigns it to the RetainMission field.
func (o *UpdateTemplateRequest) SetRetainMission(v RetainMission) {
	o.RetainMission = &v
}

// GetReflectMission returns the ReflectMission field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetReflectMission() ReflectMission {
	if o == nil || IsNil(o.ReflectMission) {
		var ret ReflectMission
		return ret
	}
	return *o.ReflectMission
}

// GetReflectMissionOk returns a tuple with the ReflectMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetReflectMissionOk() (*ReflectMission, bool) {
	if o == nil || IsNil(o.ReflectMission) {
		return nil, false
	}
	return o.ReflectMission, true
}

// HasReflectMission returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasReflectMission() bool {
	if o != nil && !IsNil(o.ReflectMission) {
		return true
	}

	return false
}

// SetReflectMission gets a reference to the given ReflectMission and assigns it to the ReflectMission field.
func (o *UpdateTemplateRequest) SetReflectMission(v ReflectMission) {
	o.ReflectMission = &v
}

// GetObservationsMission returns the ObservationsMission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetObservationsMission() ObservationsMission {
	if o == nil || IsNil(o.ObservationsMission.Get()) {
		var ret ObservationsMission
		return ret
	}
	return *o.ObservationsMission.Get()
}

// GetObservationsMissionOk returns a tuple with the ObservationsMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetObservationsMissionOk() (*ObservationsMission, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservationsMission.Get(), o.ObservationsMission.IsSet()
}

// HasObservationsMission returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasObservationsMission() bool {
	if o != nil && o.ObservationsMission.IsSet() {
		return true
	}

	return false
}

// SetObservationsMission gets a reference to the given NullableObservationsMission and assigns it to the ObservationsMission field.
func (o *UpdateTemplateRequest) SetObservationsMission(v ObservationsMission) {
	o.ObservationsMission.Set(&v)
}
// SetObservationsMissionNil sets the value for ObservationsMission to be an explicit nil
func (o *UpdateTemplateRequest) SetObservationsMissionNil() {
	o.ObservationsMission.Set(nil)
}

// UnsetObservationsMission ensures that no value is present for ObservationsMission, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetObservationsMission() {
	o.ObservationsMission.Unset()
}

// GetRetainExtractionMode returns the RetainExtractionMode field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetRetainExtractionMode() RetainExtractionMode {
	if o == nil || IsNil(o.RetainExtractionMode) {
		var ret RetainExtractionMode
		return ret
	}
	return *o.RetainExtractionMode
}

// GetRetainExtractionModeOk returns a tuple with the RetainExtractionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetRetainExtractionModeOk() (*RetainExtractionMode, bool) {
	if o == nil || IsNil(o.RetainExtractionMode) {
		return nil, false
	}
	return o.RetainExtractionMode, true
}

// HasRetainExtractionMode returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainExtractionMode() bool {
	if o != nil && !IsNil(o.RetainExtractionMode) {
		return true
	}

	return false
}

// SetRetainExtractionMode gets a reference to the given RetainExtractionMode and assigns it to the RetainExtractionMode field.
func (o *UpdateTemplateRequest) SetRetainExtractionMode(v RetainExtractionMode) {
	o.RetainExtractionMode = &v
}

// GetRetainCustomInstructions returns the RetainCustomInstructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetRetainCustomInstructions() RetainCustomInstructions {
	if o == nil || IsNil(o.RetainCustomInstructions.Get()) {
		var ret RetainCustomInstructions
		return ret
	}
	return *o.RetainCustomInstructions.Get()
}

// GetRetainCustomInstructionsOk returns a tuple with the RetainCustomInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetRetainCustomInstructionsOk() (*RetainCustomInstructions, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainCustomInstructions.Get(), o.RetainCustomInstructions.IsSet()
}

// HasRetainCustomInstructions returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainCustomInstructions() bool {
	if o != nil && o.RetainCustomInstructions.IsSet() {
		return true
	}

	return false
}

// SetRetainCustomInstructions gets a reference to the given NullableRetainCustomInstructions and assigns it to the RetainCustomInstructions field.
func (o *UpdateTemplateRequest) SetRetainCustomInstructions(v RetainCustomInstructions) {
	o.RetainCustomInstructions.Set(&v)
}
// SetRetainCustomInstructionsNil sets the value for RetainCustomInstructions to be an explicit nil
func (o *UpdateTemplateRequest) SetRetainCustomInstructionsNil() {
	o.RetainCustomInstructions.Set(nil)
}

// UnsetRetainCustomInstructions ensures that no value is present for RetainCustomInstructions, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetRetainCustomInstructions() {
	o.RetainCustomInstructions.Unset()
}

// GetRetainChunkSize returns the RetainChunkSize field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetRetainChunkSize() RetainChunkSize {
	if o == nil || IsNil(o.RetainChunkSize) {
		var ret RetainChunkSize
		return ret
	}
	return *o.RetainChunkSize
}

// GetRetainChunkSizeOk returns a tuple with the RetainChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetRetainChunkSizeOk() (*RetainChunkSize, bool) {
	if o == nil || IsNil(o.RetainChunkSize) {
		return nil, false
	}
	return o.RetainChunkSize, true
}

// HasRetainChunkSize returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainChunkSize() bool {
	if o != nil && !IsNil(o.RetainChunkSize) {
		return true
	}

	return false
}

// SetRetainChunkSize gets a reference to the given RetainChunkSize and assigns it to the RetainChunkSize field.
func (o *UpdateTemplateRequest) SetRetainChunkSize(v RetainChunkSize) {
	o.RetainChunkSize = &v
}

// GetRetainDefaultStrategy returns the RetainDefaultStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetRetainDefaultStrategy() RetainDefaultStrategy {
	if o == nil || IsNil(o.RetainDefaultStrategy.Get()) {
		var ret RetainDefaultStrategy
		return ret
	}
	return *o.RetainDefaultStrategy.Get()
}

// GetRetainDefaultStrategyOk returns a tuple with the RetainDefaultStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetRetainDefaultStrategyOk() (*RetainDefaultStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainDefaultStrategy.Get(), o.RetainDefaultStrategy.IsSet()
}

// HasRetainDefaultStrategy returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainDefaultStrategy() bool {
	if o != nil && o.RetainDefaultStrategy.IsSet() {
		return true
	}

	return false
}

// SetRetainDefaultStrategy gets a reference to the given NullableRetainDefaultStrategy and assigns it to the RetainDefaultStrategy field.
func (o *UpdateTemplateRequest) SetRetainDefaultStrategy(v RetainDefaultStrategy) {
	o.RetainDefaultStrategy.Set(&v)
}
// SetRetainDefaultStrategyNil sets the value for RetainDefaultStrategy to be an explicit nil
func (o *UpdateTemplateRequest) SetRetainDefaultStrategyNil() {
	o.RetainDefaultStrategy.Set(nil)
}

// UnsetRetainDefaultStrategy ensures that no value is present for RetainDefaultStrategy, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetRetainDefaultStrategy() {
	o.RetainDefaultStrategy.Unset()
}

// GetRetainStrategies returns the RetainStrategies field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetRetainStrategies() RetainStrategies {
	if o == nil || IsNil(o.RetainStrategies) {
		var ret RetainStrategies
		return ret
	}
	return *o.RetainStrategies
}

// GetRetainStrategiesOk returns a tuple with the RetainStrategies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetRetainStrategiesOk() (*RetainStrategies, bool) {
	if o == nil || IsNil(o.RetainStrategies) {
		return nil, false
	}
	return o.RetainStrategies, true
}

// HasRetainStrategies returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRetainStrategies() bool {
	if o != nil && !IsNil(o.RetainStrategies) {
		return true
	}

	return false
}

// SetRetainStrategies gets a reference to the given RetainStrategies and assigns it to the RetainStrategies field.
func (o *UpdateTemplateRequest) SetRetainStrategies(v RetainStrategies) {
	o.RetainStrategies = &v
}

// GetEntityLabels returns the EntityLabels field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetEntityLabels() EntityLabels {
	if o == nil || IsNil(o.EntityLabels) {
		var ret EntityLabels
		return ret
	}
	return *o.EntityLabels
}

// GetEntityLabelsOk returns a tuple with the EntityLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetEntityLabelsOk() (*EntityLabels, bool) {
	if o == nil || IsNil(o.EntityLabels) {
		return nil, false
	}
	return o.EntityLabels, true
}

// HasEntityLabels returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasEntityLabels() bool {
	if o != nil && !IsNil(o.EntityLabels) {
		return true
	}

	return false
}

// SetEntityLabels gets a reference to the given EntityLabels and assigns it to the EntityLabels field.
func (o *UpdateTemplateRequest) SetEntityLabels(v EntityLabels) {
	o.EntityLabels = &v
}

// GetEntitiesAllowFreeForm returns the EntitiesAllowFreeForm field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetEntitiesAllowFreeForm() EntitiesAllowFreeForm {
	if o == nil || IsNil(o.EntitiesAllowFreeForm) {
		var ret EntitiesAllowFreeForm
		return ret
	}
	return *o.EntitiesAllowFreeForm
}

// GetEntitiesAllowFreeFormOk returns a tuple with the EntitiesAllowFreeForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetEntitiesAllowFreeFormOk() (*EntitiesAllowFreeForm, bool) {
	if o == nil || IsNil(o.EntitiesAllowFreeForm) {
		return nil, false
	}
	return o.EntitiesAllowFreeForm, true
}

// HasEntitiesAllowFreeForm returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasEntitiesAllowFreeForm() bool {
	if o != nil && !IsNil(o.EntitiesAllowFreeForm) {
		return true
	}

	return false
}

// SetEntitiesAllowFreeForm gets a reference to the given EntitiesAllowFreeForm and assigns it to the EntitiesAllowFreeForm field.
func (o *UpdateTemplateRequest) SetEntitiesAllowFreeForm(v EntitiesAllowFreeForm) {
	o.EntitiesAllowFreeForm = &v
}

// GetEnableObservations returns the EnableObservations field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetEnableObservations() EnableObservations {
	if o == nil || IsNil(o.EnableObservations) {
		var ret EnableObservations
		return ret
	}
	return *o.EnableObservations
}

// GetEnableObservationsOk returns a tuple with the EnableObservations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetEnableObservationsOk() (*EnableObservations, bool) {
	if o == nil || IsNil(o.EnableObservations) {
		return nil, false
	}
	return o.EnableObservations, true
}

// HasEnableObservations returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasEnableObservations() bool {
	if o != nil && !IsNil(o.EnableObservations) {
		return true
	}

	return false
}

// SetEnableObservations gets a reference to the given EnableObservations and assigns it to the EnableObservations field.
func (o *UpdateTemplateRequest) SetEnableObservations(v EnableObservations) {
	o.EnableObservations = &v
}

// GetConsolidationLlmBatchSize returns the ConsolidationLlmBatchSize field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetConsolidationLlmBatchSize() ConsolidationLlmBatchSize {
	if o == nil || IsNil(o.ConsolidationLlmBatchSize) {
		var ret ConsolidationLlmBatchSize
		return ret
	}
	return *o.ConsolidationLlmBatchSize
}

// GetConsolidationLlmBatchSizeOk returns a tuple with the ConsolidationLlmBatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetConsolidationLlmBatchSizeOk() (*ConsolidationLlmBatchSize, bool) {
	if o == nil || IsNil(o.ConsolidationLlmBatchSize) {
		return nil, false
	}
	return o.ConsolidationLlmBatchSize, true
}

// HasConsolidationLlmBatchSize returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasConsolidationLlmBatchSize() bool {
	if o != nil && !IsNil(o.ConsolidationLlmBatchSize) {
		return true
	}

	return false
}

// SetConsolidationLlmBatchSize gets a reference to the given ConsolidationLlmBatchSize and assigns it to the ConsolidationLlmBatchSize field.
func (o *UpdateTemplateRequest) SetConsolidationLlmBatchSize(v ConsolidationLlmBatchSize) {
	o.ConsolidationLlmBatchSize = &v
}

// GetConsolidationSourceFactsMaxTokens returns the ConsolidationSourceFactsMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetConsolidationSourceFactsMaxTokens() ConsolidationSourceFactsMaxTokens {
	if o == nil || IsNil(o.ConsolidationSourceFactsMaxTokens.Get()) {
		var ret ConsolidationSourceFactsMaxTokens
		return ret
	}
	return *o.ConsolidationSourceFactsMaxTokens.Get()
}

// GetConsolidationSourceFactsMaxTokensOk returns a tuple with the ConsolidationSourceFactsMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetConsolidationSourceFactsMaxTokensOk() (*ConsolidationSourceFactsMaxTokens, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsolidationSourceFactsMaxTokens.Get(), o.ConsolidationSourceFactsMaxTokens.IsSet()
}

// HasConsolidationSourceFactsMaxTokens returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasConsolidationSourceFactsMaxTokens() bool {
	if o != nil && o.ConsolidationSourceFactsMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetConsolidationSourceFactsMaxTokens gets a reference to the given NullableConsolidationSourceFactsMaxTokens and assigns it to the ConsolidationSourceFactsMaxTokens field.
func (o *UpdateTemplateRequest) SetConsolidationSourceFactsMaxTokens(v ConsolidationSourceFactsMaxTokens) {
	o.ConsolidationSourceFactsMaxTokens.Set(&v)
}
// SetConsolidationSourceFactsMaxTokensNil sets the value for ConsolidationSourceFactsMaxTokens to be an explicit nil
func (o *UpdateTemplateRequest) SetConsolidationSourceFactsMaxTokensNil() {
	o.ConsolidationSourceFactsMaxTokens.Set(nil)
}

// UnsetConsolidationSourceFactsMaxTokens ensures that no value is present for ConsolidationSourceFactsMaxTokens, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetConsolidationSourceFactsMaxTokens() {
	o.ConsolidationSourceFactsMaxTokens.Unset()
}

// GetConsolidationSourceFactsMaxTokensPerObservation returns the ConsolidationSourceFactsMaxTokensPerObservation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTemplateRequest) GetConsolidationSourceFactsMaxTokensPerObservation() ConsolidationSourceFactsMaxTokensPerObservation {
	if o == nil || IsNil(o.ConsolidationSourceFactsMaxTokensPerObservation.Get()) {
		var ret ConsolidationSourceFactsMaxTokensPerObservation
		return ret
	}
	return *o.ConsolidationSourceFactsMaxTokensPerObservation.Get()
}

// GetConsolidationSourceFactsMaxTokensPerObservationOk returns a tuple with the ConsolidationSourceFactsMaxTokensPerObservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateRequest) GetConsolidationSourceFactsMaxTokensPerObservationOk() (*ConsolidationSourceFactsMaxTokensPerObservation, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsolidationSourceFactsMaxTokensPerObservation.Get(), o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet()
}

// HasConsolidationSourceFactsMaxTokensPerObservation returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasConsolidationSourceFactsMaxTokensPerObservation() bool {
	if o != nil && o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet() {
		return true
	}

	return false
}

// SetConsolidationSourceFactsMaxTokensPerObservation gets a reference to the given NullableConsolidationSourceFactsMaxTokensPerObservation and assigns it to the ConsolidationSourceFactsMaxTokensPerObservation field.
func (o *UpdateTemplateRequest) SetConsolidationSourceFactsMaxTokensPerObservation(v ConsolidationSourceFactsMaxTokensPerObservation) {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Set(&v)
}
// SetConsolidationSourceFactsMaxTokensPerObservationNil sets the value for ConsolidationSourceFactsMaxTokensPerObservation to be an explicit nil
func (o *UpdateTemplateRequest) SetConsolidationSourceFactsMaxTokensPerObservationNil() {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Set(nil)
}

// UnsetConsolidationSourceFactsMaxTokensPerObservation ensures that no value is present for ConsolidationSourceFactsMaxTokensPerObservation, not even an explicit nil
func (o *UpdateTemplateRequest) UnsetConsolidationSourceFactsMaxTokensPerObservation() {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Unset()
}

// GetDispositionSkepticism returns the DispositionSkepticism field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetDispositionSkepticism() DispositionSkepticism {
	if o == nil || IsNil(o.DispositionSkepticism) {
		var ret DispositionSkepticism
		return ret
	}
	return *o.DispositionSkepticism
}

// GetDispositionSkepticismOk returns a tuple with the DispositionSkepticism field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetDispositionSkepticismOk() (*DispositionSkepticism, bool) {
	if o == nil || IsNil(o.DispositionSkepticism) {
		return nil, false
	}
	return o.DispositionSkepticism, true
}

// HasDispositionSkepticism returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasDispositionSkepticism() bool {
	if o != nil && !IsNil(o.DispositionSkepticism) {
		return true
	}

	return false
}

// SetDispositionSkepticism gets a reference to the given DispositionSkepticism and assigns it to the DispositionSkepticism field.
func (o *UpdateTemplateRequest) SetDispositionSkepticism(v DispositionSkepticism) {
	o.DispositionSkepticism = &v
}

// GetDispositionLiteralism returns the DispositionLiteralism field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetDispositionLiteralism() DispositionLiteralism {
	if o == nil || IsNil(o.DispositionLiteralism) {
		var ret DispositionLiteralism
		return ret
	}
	return *o.DispositionLiteralism
}

// GetDispositionLiteralismOk returns a tuple with the DispositionLiteralism field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetDispositionLiteralismOk() (*DispositionLiteralism, bool) {
	if o == nil || IsNil(o.DispositionLiteralism) {
		return nil, false
	}
	return o.DispositionLiteralism, true
}

// HasDispositionLiteralism returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasDispositionLiteralism() bool {
	if o != nil && !IsNil(o.DispositionLiteralism) {
		return true
	}

	return false
}

// SetDispositionLiteralism gets a reference to the given DispositionLiteralism and assigns it to the DispositionLiteralism field.
func (o *UpdateTemplateRequest) SetDispositionLiteralism(v DispositionLiteralism) {
	o.DispositionLiteralism = &v
}

// GetDispositionEmpathy returns the DispositionEmpathy field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetDispositionEmpathy() DispositionEmpathy {
	if o == nil || IsNil(o.DispositionEmpathy) {
		var ret DispositionEmpathy
		return ret
	}
	return *o.DispositionEmpathy
}

// GetDispositionEmpathyOk returns a tuple with the DispositionEmpathy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetDispositionEmpathyOk() (*DispositionEmpathy, bool) {
	if o == nil || IsNil(o.DispositionEmpathy) {
		return nil, false
	}
	return o.DispositionEmpathy, true
}

// HasDispositionEmpathy returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasDispositionEmpathy() bool {
	if o != nil && !IsNil(o.DispositionEmpathy) {
		return true
	}

	return false
}

// SetDispositionEmpathy gets a reference to the given DispositionEmpathy and assigns it to the DispositionEmpathy field.
func (o *UpdateTemplateRequest) SetDispositionEmpathy(v DispositionEmpathy) {
	o.DispositionEmpathy = &v
}

// GetDirectiveSeeds returns the DirectiveSeeds field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetDirectiveSeeds() DirectiveSeeds {
	if o == nil || IsNil(o.DirectiveSeeds) {
		var ret DirectiveSeeds
		return ret
	}
	return *o.DirectiveSeeds
}

// GetDirectiveSeedsOk returns a tuple with the DirectiveSeeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetDirectiveSeedsOk() (*DirectiveSeeds, bool) {
	if o == nil || IsNil(o.DirectiveSeeds) {
		return nil, false
	}
	return o.DirectiveSeeds, true
}

// HasDirectiveSeeds returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasDirectiveSeeds() bool {
	if o != nil && !IsNil(o.DirectiveSeeds) {
		return true
	}

	return false
}

// SetDirectiveSeeds gets a reference to the given DirectiveSeeds and assigns it to the DirectiveSeeds field.
func (o *UpdateTemplateRequest) SetDirectiveSeeds(v DirectiveSeeds) {
	o.DirectiveSeeds = &v
}

// GetMentalModelSeeds returns the MentalModelSeeds field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetMentalModelSeeds() MentalModelSeeds {
	if o == nil || IsNil(o.MentalModelSeeds) {
		var ret MentalModelSeeds
		return ret
	}
	return *o.MentalModelSeeds
}

// GetMentalModelSeedsOk returns a tuple with the MentalModelSeeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetMentalModelSeedsOk() (*MentalModelSeeds, bool) {
	if o == nil || IsNil(o.MentalModelSeeds) {
		return nil, false
	}
	return o.MentalModelSeeds, true
}

// HasMentalModelSeeds returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasMentalModelSeeds() bool {
	if o != nil && !IsNil(o.MentalModelSeeds) {
		return true
	}

	return false
}

// SetMentalModelSeeds gets a reference to the given MentalModelSeeds and assigns it to the MentalModelSeeds field.
func (o *UpdateTemplateRequest) SetMentalModelSeeds(v MentalModelSeeds) {
	o.MentalModelSeeds = &v
}

func (o UpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.MinHindclawVersion) {
		toSerialize["min_hindclaw_version"] = o.MinHindclawVersion
	}
	if o.MinHindsightVersion.IsSet() {
		toSerialize["min_hindsight_version"] = o.MinHindsightVersion.Get()
	}
	if !IsNil(o.RetainMission) {
		toSerialize["retain_mission"] = o.RetainMission
	}
	if !IsNil(o.ReflectMission) {
		toSerialize["reflect_mission"] = o.ReflectMission
	}
	if o.ObservationsMission.IsSet() {
		toSerialize["observations_mission"] = o.ObservationsMission.Get()
	}
	if !IsNil(o.RetainExtractionMode) {
		toSerialize["retain_extraction_mode"] = o.RetainExtractionMode
	}
	if o.RetainCustomInstructions.IsSet() {
		toSerialize["retain_custom_instructions"] = o.RetainCustomInstructions.Get()
	}
	if !IsNil(o.RetainChunkSize) {
		toSerialize["retain_chunk_size"] = o.RetainChunkSize
	}
	if o.RetainDefaultStrategy.IsSet() {
		toSerialize["retain_default_strategy"] = o.RetainDefaultStrategy.Get()
	}
	if !IsNil(o.RetainStrategies) {
		toSerialize["retain_strategies"] = o.RetainStrategies
	}
	if !IsNil(o.EntityLabels) {
		toSerialize["entity_labels"] = o.EntityLabels
	}
	if !IsNil(o.EntitiesAllowFreeForm) {
		toSerialize["entities_allow_free_form"] = o.EntitiesAllowFreeForm
	}
	if !IsNil(o.EnableObservations) {
		toSerialize["enable_observations"] = o.EnableObservations
	}
	if !IsNil(o.ConsolidationLlmBatchSize) {
		toSerialize["consolidation_llm_batch_size"] = o.ConsolidationLlmBatchSize
	}
	if o.ConsolidationSourceFactsMaxTokens.IsSet() {
		toSerialize["consolidation_source_facts_max_tokens"] = o.ConsolidationSourceFactsMaxTokens.Get()
	}
	if o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet() {
		toSerialize["consolidation_source_facts_max_tokens_per_observation"] = o.ConsolidationSourceFactsMaxTokensPerObservation.Get()
	}
	if !IsNil(o.DispositionSkepticism) {
		toSerialize["disposition_skepticism"] = o.DispositionSkepticism
	}
	if !IsNil(o.DispositionLiteralism) {
		toSerialize["disposition_literalism"] = o.DispositionLiteralism
	}
	if !IsNil(o.DispositionEmpathy) {
		toSerialize["disposition_empathy"] = o.DispositionEmpathy
	}
	if !IsNil(o.DirectiveSeeds) {
		toSerialize["directive_seeds"] = o.DirectiveSeeds
	}
	if !IsNil(o.MentalModelSeeds) {
		toSerialize["mental_model_seeds"] = o.MentalModelSeeds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateTemplateRequest := _UpdateTemplateRequest{}

	err = json.Unmarshal(data, &varUpdateTemplateRequest)

	if err != nil {
		return err
	}

	*o = UpdateTemplateRequest(varUpdateTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "author")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "min_hindclaw_version")
		delete(additionalProperties, "min_hindsight_version")
		delete(additionalProperties, "retain_mission")
		delete(additionalProperties, "reflect_mission")
		delete(additionalProperties, "observations_mission")
		delete(additionalProperties, "retain_extraction_mode")
		delete(additionalProperties, "retain_custom_instructions")
		delete(additionalProperties, "retain_chunk_size")
		delete(additionalProperties, "retain_default_strategy")
		delete(additionalProperties, "retain_strategies")
		delete(additionalProperties, "entity_labels")
		delete(additionalProperties, "entities_allow_free_form")
		delete(additionalProperties, "enable_observations")
		delete(additionalProperties, "consolidation_llm_batch_size")
		delete(additionalProperties, "consolidation_source_facts_max_tokens")
		delete(additionalProperties, "consolidation_source_facts_max_tokens_per_observation")
		delete(additionalProperties, "disposition_skepticism")
		delete(additionalProperties, "disposition_literalism")
		delete(additionalProperties, "disposition_empathy")
		delete(additionalProperties, "directive_seeds")
		delete(additionalProperties, "mental_model_seeds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateTemplateRequest struct {
	value *UpdateTemplateRequest
	isSet bool
}

func (v NullableUpdateTemplateRequest) Get() *UpdateTemplateRequest {
	return v.value
}

func (v *NullableUpdateTemplateRequest) Set(val *UpdateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTemplateRequest(val *UpdateTemplateRequest) *NullableUpdateTemplateRequest {
	return &NullableUpdateTemplateRequest{value: val, isSet: true}
}

func (v NullableUpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


