/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateRequest{}

// CreateTemplateRequest Request to create a custom template.
type CreateTemplateRequest struct {
	Id string `json:"id"`
	Scope string `json:"scope"`
	Description *string `json:"description,omitempty"`
	Author *string `json:"author,omitempty"`
	Tags []string `json:"tags,omitempty"`
	MinHindclawVersion string `json:"min_hindclaw_version"`
	MinHindsightVersion NullableMinHindsightVersion `json:"min_hindsight_version,omitempty"`
	RetainMission string `json:"retain_mission"`
	ReflectMission string `json:"reflect_mission"`
	ObservationsMission NullableObservationsMission `json:"observations_mission,omitempty"`
	RetainExtractionMode *string `json:"retain_extraction_mode,omitempty"`
	RetainCustomInstructions NullableRetainCustomInstructions `json:"retain_custom_instructions,omitempty"`
	RetainChunkSize *RetainChunkSize `json:"retain_chunk_size,omitempty"`
	RetainDefaultStrategy NullableRetainDefaultStrategy `json:"retain_default_strategy,omitempty"`
	RetainStrategies map[string]interface{} `json:"retain_strategies,omitempty"`
	EntityLabels []EntityLabel `json:"entity_labels,omitempty"`
	EntitiesAllowFreeForm *bool `json:"entities_allow_free_form,omitempty"`
	EnableObservations *bool `json:"enable_observations,omitempty"`
	ConsolidationLlmBatchSize *ConsolidationLlmBatchSize `json:"consolidation_llm_batch_size,omitempty"`
	ConsolidationSourceFactsMaxTokens NullableConsolidationSourceFactsMaxTokens `json:"consolidation_source_facts_max_tokens,omitempty"`
	ConsolidationSourceFactsMaxTokensPerObservation NullableConsolidationSourceFactsMaxTokensPerObservation `json:"consolidation_source_facts_max_tokens_per_observation,omitempty"`
	DispositionSkepticism *int32 `json:"disposition_skepticism,omitempty"`
	DispositionLiteralism *int32 `json:"disposition_literalism,omitempty"`
	DispositionEmpathy *int32 `json:"disposition_empathy,omitempty"`
	DirectiveSeeds []DirectiveSeed `json:"directive_seeds,omitempty"`
	MentalModelSeeds []MentalModelSeed `json:"mental_model_seeds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateTemplateRequest CreateTemplateRequest

// NewCreateTemplateRequest instantiates a new CreateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateRequest(id string, scope string, minHindclawVersion string, retainMission string, reflectMission string) *CreateTemplateRequest {
	this := CreateTemplateRequest{}
	this.Id = id
	this.Scope = scope
	var description string = ""
	this.Description = &description
	var author string = ""
	this.Author = &author
	this.MinHindclawVersion = minHindclawVersion
	this.RetainMission = retainMission
	this.ReflectMission = reflectMission
	var retainExtractionMode string = "concise"
	this.RetainExtractionMode = &retainExtractionMode
	var entitiesAllowFreeForm bool = true
	this.EntitiesAllowFreeForm = &entitiesAllowFreeForm
	var enableObservations bool = true
	this.EnableObservations = &enableObservations
	var dispositionSkepticism int32 = 3
	this.DispositionSkepticism = &dispositionSkepticism
	var dispositionLiteralism int32 = 3
	this.DispositionLiteralism = &dispositionLiteralism
	var dispositionEmpathy int32 = 3
	this.DispositionEmpathy = &dispositionEmpathy
	return &this
}

// NewCreateTemplateRequestWithDefaults instantiates a new CreateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateRequestWithDefaults() *CreateTemplateRequest {
	this := CreateTemplateRequest{}
	var description string = ""
	this.Description = &description
	var author string = ""
	this.Author = &author
	var retainExtractionMode string = "concise"
	this.RetainExtractionMode = &retainExtractionMode
	var entitiesAllowFreeForm bool = true
	this.EntitiesAllowFreeForm = &entitiesAllowFreeForm
	var enableObservations bool = true
	this.EnableObservations = &enableObservations
	var dispositionSkepticism int32 = 3
	this.DispositionSkepticism = &dispositionSkepticism
	var dispositionLiteralism int32 = 3
	this.DispositionLiteralism = &dispositionLiteralism
	var dispositionEmpathy int32 = 3
	this.DispositionEmpathy = &dispositionEmpathy
	return &this
}

// GetId returns the Id field value
func (o *CreateTemplateRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateTemplateRequest) SetId(v string) {
	o.Id = v
}

// GetScope returns the Scope field value
func (o *CreateTemplateRequest) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *CreateTemplateRequest) SetScope(v string) {
	o.Scope = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTemplateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *CreateTemplateRequest) SetAuthor(v string) {
	o.Author = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateTemplateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetMinHindclawVersion returns the MinHindclawVersion field value
func (o *CreateTemplateRequest) GetMinHindclawVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinHindclawVersion
}

// GetMinHindclawVersionOk returns a tuple with the MinHindclawVersion field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetMinHindclawVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinHindclawVersion, true
}

// SetMinHindclawVersion sets field value
func (o *CreateTemplateRequest) SetMinHindclawVersion(v string) {
	o.MinHindclawVersion = v
}

// GetMinHindsightVersion returns the MinHindsightVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetMinHindsightVersion() MinHindsightVersion {
	if o == nil || IsNil(o.MinHindsightVersion.Get()) {
		var ret MinHindsightVersion
		return ret
	}
	return *o.MinHindsightVersion.Get()
}

// GetMinHindsightVersionOk returns a tuple with the MinHindsightVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetMinHindsightVersionOk() (*MinHindsightVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinHindsightVersion.Get(), o.MinHindsightVersion.IsSet()
}

// HasMinHindsightVersion returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasMinHindsightVersion() bool {
	if o != nil && o.MinHindsightVersion.IsSet() {
		return true
	}

	return false
}

// SetMinHindsightVersion gets a reference to the given NullableMinHindsightVersion and assigns it to the MinHindsightVersion field.
func (o *CreateTemplateRequest) SetMinHindsightVersion(v MinHindsightVersion) {
	o.MinHindsightVersion.Set(&v)
}
// SetMinHindsightVersionNil sets the value for MinHindsightVersion to be an explicit nil
func (o *CreateTemplateRequest) SetMinHindsightVersionNil() {
	o.MinHindsightVersion.Set(nil)
}

// UnsetMinHindsightVersion ensures that no value is present for MinHindsightVersion, not even an explicit nil
func (o *CreateTemplateRequest) UnsetMinHindsightVersion() {
	o.MinHindsightVersion.Unset()
}

// GetRetainMission returns the RetainMission field value
func (o *CreateTemplateRequest) GetRetainMission() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetainMission
}

// GetRetainMissionOk returns a tuple with the RetainMission field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetRetainMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetainMission, true
}

// SetRetainMission sets field value
func (o *CreateTemplateRequest) SetRetainMission(v string) {
	o.RetainMission = v
}

// GetReflectMission returns the ReflectMission field value
func (o *CreateTemplateRequest) GetReflectMission() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReflectMission
}

// GetReflectMissionOk returns a tuple with the ReflectMission field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetReflectMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReflectMission, true
}

// SetReflectMission sets field value
func (o *CreateTemplateRequest) SetReflectMission(v string) {
	o.ReflectMission = v
}

// GetObservationsMission returns the ObservationsMission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetObservationsMission() ObservationsMission {
	if o == nil || IsNil(o.ObservationsMission.Get()) {
		var ret ObservationsMission
		return ret
	}
	return *o.ObservationsMission.Get()
}

// GetObservationsMissionOk returns a tuple with the ObservationsMission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetObservationsMissionOk() (*ObservationsMission, bool) {
	if o == nil {
		return nil, false
	}
	return o.ObservationsMission.Get(), o.ObservationsMission.IsSet()
}

// HasObservationsMission returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasObservationsMission() bool {
	if o != nil && o.ObservationsMission.IsSet() {
		return true
	}

	return false
}

// SetObservationsMission gets a reference to the given NullableObservationsMission and assigns it to the ObservationsMission field.
func (o *CreateTemplateRequest) SetObservationsMission(v ObservationsMission) {
	o.ObservationsMission.Set(&v)
}
// SetObservationsMissionNil sets the value for ObservationsMission to be an explicit nil
func (o *CreateTemplateRequest) SetObservationsMissionNil() {
	o.ObservationsMission.Set(nil)
}

// UnsetObservationsMission ensures that no value is present for ObservationsMission, not even an explicit nil
func (o *CreateTemplateRequest) UnsetObservationsMission() {
	o.ObservationsMission.Unset()
}

// GetRetainExtractionMode returns the RetainExtractionMode field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetRetainExtractionMode() string {
	if o == nil || IsNil(o.RetainExtractionMode) {
		var ret string
		return ret
	}
	return *o.RetainExtractionMode
}

// GetRetainExtractionModeOk returns a tuple with the RetainExtractionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetRetainExtractionModeOk() (*string, bool) {
	if o == nil || IsNil(o.RetainExtractionMode) {
		return nil, false
	}
	return o.RetainExtractionMode, true
}

// HasRetainExtractionMode returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasRetainExtractionMode() bool {
	if o != nil && !IsNil(o.RetainExtractionMode) {
		return true
	}

	return false
}

// SetRetainExtractionMode gets a reference to the given string and assigns it to the RetainExtractionMode field.
func (o *CreateTemplateRequest) SetRetainExtractionMode(v string) {
	o.RetainExtractionMode = &v
}

// GetRetainCustomInstructions returns the RetainCustomInstructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetRetainCustomInstructions() RetainCustomInstructions {
	if o == nil || IsNil(o.RetainCustomInstructions.Get()) {
		var ret RetainCustomInstructions
		return ret
	}
	return *o.RetainCustomInstructions.Get()
}

// GetRetainCustomInstructionsOk returns a tuple with the RetainCustomInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetRetainCustomInstructionsOk() (*RetainCustomInstructions, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainCustomInstructions.Get(), o.RetainCustomInstructions.IsSet()
}

// HasRetainCustomInstructions returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasRetainCustomInstructions() bool {
	if o != nil && o.RetainCustomInstructions.IsSet() {
		return true
	}

	return false
}

// SetRetainCustomInstructions gets a reference to the given NullableRetainCustomInstructions and assigns it to the RetainCustomInstructions field.
func (o *CreateTemplateRequest) SetRetainCustomInstructions(v RetainCustomInstructions) {
	o.RetainCustomInstructions.Set(&v)
}
// SetRetainCustomInstructionsNil sets the value for RetainCustomInstructions to be an explicit nil
func (o *CreateTemplateRequest) SetRetainCustomInstructionsNil() {
	o.RetainCustomInstructions.Set(nil)
}

// UnsetRetainCustomInstructions ensures that no value is present for RetainCustomInstructions, not even an explicit nil
func (o *CreateTemplateRequest) UnsetRetainCustomInstructions() {
	o.RetainCustomInstructions.Unset()
}

// GetRetainChunkSize returns the RetainChunkSize field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetRetainChunkSize() RetainChunkSize {
	if o == nil || IsNil(o.RetainChunkSize) {
		var ret RetainChunkSize
		return ret
	}
	return *o.RetainChunkSize
}

// GetRetainChunkSizeOk returns a tuple with the RetainChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetRetainChunkSizeOk() (*RetainChunkSize, bool) {
	if o == nil || IsNil(o.RetainChunkSize) {
		return nil, false
	}
	return o.RetainChunkSize, true
}

// HasRetainChunkSize returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasRetainChunkSize() bool {
	if o != nil && !IsNil(o.RetainChunkSize) {
		return true
	}

	return false
}

// SetRetainChunkSize gets a reference to the given RetainChunkSize and assigns it to the RetainChunkSize field.
func (o *CreateTemplateRequest) SetRetainChunkSize(v RetainChunkSize) {
	o.RetainChunkSize = &v
}

// GetRetainDefaultStrategy returns the RetainDefaultStrategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetRetainDefaultStrategy() RetainDefaultStrategy {
	if o == nil || IsNil(o.RetainDefaultStrategy.Get()) {
		var ret RetainDefaultStrategy
		return ret
	}
	return *o.RetainDefaultStrategy.Get()
}

// GetRetainDefaultStrategyOk returns a tuple with the RetainDefaultStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetRetainDefaultStrategyOk() (*RetainDefaultStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetainDefaultStrategy.Get(), o.RetainDefaultStrategy.IsSet()
}

// HasRetainDefaultStrategy returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasRetainDefaultStrategy() bool {
	if o != nil && o.RetainDefaultStrategy.IsSet() {
		return true
	}

	return false
}

// SetRetainDefaultStrategy gets a reference to the given NullableRetainDefaultStrategy and assigns it to the RetainDefaultStrategy field.
func (o *CreateTemplateRequest) SetRetainDefaultStrategy(v RetainDefaultStrategy) {
	o.RetainDefaultStrategy.Set(&v)
}
// SetRetainDefaultStrategyNil sets the value for RetainDefaultStrategy to be an explicit nil
func (o *CreateTemplateRequest) SetRetainDefaultStrategyNil() {
	o.RetainDefaultStrategy.Set(nil)
}

// UnsetRetainDefaultStrategy ensures that no value is present for RetainDefaultStrategy, not even an explicit nil
func (o *CreateTemplateRequest) UnsetRetainDefaultStrategy() {
	o.RetainDefaultStrategy.Unset()
}

// GetRetainStrategies returns the RetainStrategies field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetRetainStrategies() map[string]interface{} {
	if o == nil || IsNil(o.RetainStrategies) {
		var ret map[string]interface{}
		return ret
	}
	return o.RetainStrategies
}

// GetRetainStrategiesOk returns a tuple with the RetainStrategies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetRetainStrategiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RetainStrategies) {
		return map[string]interface{}{}, false
	}
	return o.RetainStrategies, true
}

// HasRetainStrategies returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasRetainStrategies() bool {
	if o != nil && !IsNil(o.RetainStrategies) {
		return true
	}

	return false
}

// SetRetainStrategies gets a reference to the given map[string]interface{} and assigns it to the RetainStrategies field.
func (o *CreateTemplateRequest) SetRetainStrategies(v map[string]interface{}) {
	o.RetainStrategies = v
}

// GetEntityLabels returns the EntityLabels field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetEntityLabels() []EntityLabel {
	if o == nil || IsNil(o.EntityLabels) {
		var ret []EntityLabel
		return ret
	}
	return o.EntityLabels
}

// GetEntityLabelsOk returns a tuple with the EntityLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetEntityLabelsOk() ([]EntityLabel, bool) {
	if o == nil || IsNil(o.EntityLabels) {
		return nil, false
	}
	return o.EntityLabels, true
}

// HasEntityLabels returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasEntityLabels() bool {
	if o != nil && !IsNil(o.EntityLabels) {
		return true
	}

	return false
}

// SetEntityLabels gets a reference to the given []EntityLabel and assigns it to the EntityLabels field.
func (o *CreateTemplateRequest) SetEntityLabels(v []EntityLabel) {
	o.EntityLabels = v
}

// GetEntitiesAllowFreeForm returns the EntitiesAllowFreeForm field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetEntitiesAllowFreeForm() bool {
	if o == nil || IsNil(o.EntitiesAllowFreeForm) {
		var ret bool
		return ret
	}
	return *o.EntitiesAllowFreeForm
}

// GetEntitiesAllowFreeFormOk returns a tuple with the EntitiesAllowFreeForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetEntitiesAllowFreeFormOk() (*bool, bool) {
	if o == nil || IsNil(o.EntitiesAllowFreeForm) {
		return nil, false
	}
	return o.EntitiesAllowFreeForm, true
}

// HasEntitiesAllowFreeForm returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasEntitiesAllowFreeForm() bool {
	if o != nil && !IsNil(o.EntitiesAllowFreeForm) {
		return true
	}

	return false
}

// SetEntitiesAllowFreeForm gets a reference to the given bool and assigns it to the EntitiesAllowFreeForm field.
func (o *CreateTemplateRequest) SetEntitiesAllowFreeForm(v bool) {
	o.EntitiesAllowFreeForm = &v
}

// GetEnableObservations returns the EnableObservations field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetEnableObservations() bool {
	if o == nil || IsNil(o.EnableObservations) {
		var ret bool
		return ret
	}
	return *o.EnableObservations
}

// GetEnableObservationsOk returns a tuple with the EnableObservations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetEnableObservationsOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableObservations) {
		return nil, false
	}
	return o.EnableObservations, true
}

// HasEnableObservations returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasEnableObservations() bool {
	if o != nil && !IsNil(o.EnableObservations) {
		return true
	}

	return false
}

// SetEnableObservations gets a reference to the given bool and assigns it to the EnableObservations field.
func (o *CreateTemplateRequest) SetEnableObservations(v bool) {
	o.EnableObservations = &v
}

// GetConsolidationLlmBatchSize returns the ConsolidationLlmBatchSize field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetConsolidationLlmBatchSize() ConsolidationLlmBatchSize {
	if o == nil || IsNil(o.ConsolidationLlmBatchSize) {
		var ret ConsolidationLlmBatchSize
		return ret
	}
	return *o.ConsolidationLlmBatchSize
}

// GetConsolidationLlmBatchSizeOk returns a tuple with the ConsolidationLlmBatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetConsolidationLlmBatchSizeOk() (*ConsolidationLlmBatchSize, bool) {
	if o == nil || IsNil(o.ConsolidationLlmBatchSize) {
		return nil, false
	}
	return o.ConsolidationLlmBatchSize, true
}

// HasConsolidationLlmBatchSize returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasConsolidationLlmBatchSize() bool {
	if o != nil && !IsNil(o.ConsolidationLlmBatchSize) {
		return true
	}

	return false
}

// SetConsolidationLlmBatchSize gets a reference to the given ConsolidationLlmBatchSize and assigns it to the ConsolidationLlmBatchSize field.
func (o *CreateTemplateRequest) SetConsolidationLlmBatchSize(v ConsolidationLlmBatchSize) {
	o.ConsolidationLlmBatchSize = &v
}

// GetConsolidationSourceFactsMaxTokens returns the ConsolidationSourceFactsMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetConsolidationSourceFactsMaxTokens() ConsolidationSourceFactsMaxTokens {
	if o == nil || IsNil(o.ConsolidationSourceFactsMaxTokens.Get()) {
		var ret ConsolidationSourceFactsMaxTokens
		return ret
	}
	return *o.ConsolidationSourceFactsMaxTokens.Get()
}

// GetConsolidationSourceFactsMaxTokensOk returns a tuple with the ConsolidationSourceFactsMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetConsolidationSourceFactsMaxTokensOk() (*ConsolidationSourceFactsMaxTokens, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsolidationSourceFactsMaxTokens.Get(), o.ConsolidationSourceFactsMaxTokens.IsSet()
}

// HasConsolidationSourceFactsMaxTokens returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasConsolidationSourceFactsMaxTokens() bool {
	if o != nil && o.ConsolidationSourceFactsMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetConsolidationSourceFactsMaxTokens gets a reference to the given NullableConsolidationSourceFactsMaxTokens and assigns it to the ConsolidationSourceFactsMaxTokens field.
func (o *CreateTemplateRequest) SetConsolidationSourceFactsMaxTokens(v ConsolidationSourceFactsMaxTokens) {
	o.ConsolidationSourceFactsMaxTokens.Set(&v)
}
// SetConsolidationSourceFactsMaxTokensNil sets the value for ConsolidationSourceFactsMaxTokens to be an explicit nil
func (o *CreateTemplateRequest) SetConsolidationSourceFactsMaxTokensNil() {
	o.ConsolidationSourceFactsMaxTokens.Set(nil)
}

// UnsetConsolidationSourceFactsMaxTokens ensures that no value is present for ConsolidationSourceFactsMaxTokens, not even an explicit nil
func (o *CreateTemplateRequest) UnsetConsolidationSourceFactsMaxTokens() {
	o.ConsolidationSourceFactsMaxTokens.Unset()
}

// GetConsolidationSourceFactsMaxTokensPerObservation returns the ConsolidationSourceFactsMaxTokensPerObservation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTemplateRequest) GetConsolidationSourceFactsMaxTokensPerObservation() ConsolidationSourceFactsMaxTokensPerObservation {
	if o == nil || IsNil(o.ConsolidationSourceFactsMaxTokensPerObservation.Get()) {
		var ret ConsolidationSourceFactsMaxTokensPerObservation
		return ret
	}
	return *o.ConsolidationSourceFactsMaxTokensPerObservation.Get()
}

// GetConsolidationSourceFactsMaxTokensPerObservationOk returns a tuple with the ConsolidationSourceFactsMaxTokensPerObservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTemplateRequest) GetConsolidationSourceFactsMaxTokensPerObservationOk() (*ConsolidationSourceFactsMaxTokensPerObservation, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsolidationSourceFactsMaxTokensPerObservation.Get(), o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet()
}

// HasConsolidationSourceFactsMaxTokensPerObservation returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasConsolidationSourceFactsMaxTokensPerObservation() bool {
	if o != nil && o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet() {
		return true
	}

	return false
}

// SetConsolidationSourceFactsMaxTokensPerObservation gets a reference to the given NullableConsolidationSourceFactsMaxTokensPerObservation and assigns it to the ConsolidationSourceFactsMaxTokensPerObservation field.
func (o *CreateTemplateRequest) SetConsolidationSourceFactsMaxTokensPerObservation(v ConsolidationSourceFactsMaxTokensPerObservation) {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Set(&v)
}
// SetConsolidationSourceFactsMaxTokensPerObservationNil sets the value for ConsolidationSourceFactsMaxTokensPerObservation to be an explicit nil
func (o *CreateTemplateRequest) SetConsolidationSourceFactsMaxTokensPerObservationNil() {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Set(nil)
}

// UnsetConsolidationSourceFactsMaxTokensPerObservation ensures that no value is present for ConsolidationSourceFactsMaxTokensPerObservation, not even an explicit nil
func (o *CreateTemplateRequest) UnsetConsolidationSourceFactsMaxTokensPerObservation() {
	o.ConsolidationSourceFactsMaxTokensPerObservation.Unset()
}

// GetDispositionSkepticism returns the DispositionSkepticism field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetDispositionSkepticism() int32 {
	if o == nil || IsNil(o.DispositionSkepticism) {
		var ret int32
		return ret
	}
	return *o.DispositionSkepticism
}

// GetDispositionSkepticismOk returns a tuple with the DispositionSkepticism field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetDispositionSkepticismOk() (*int32, bool) {
	if o == nil || IsNil(o.DispositionSkepticism) {
		return nil, false
	}
	return o.DispositionSkepticism, true
}

// HasDispositionSkepticism returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasDispositionSkepticism() bool {
	if o != nil && !IsNil(o.DispositionSkepticism) {
		return true
	}

	return false
}

// SetDispositionSkepticism gets a reference to the given int32 and assigns it to the DispositionSkepticism field.
func (o *CreateTemplateRequest) SetDispositionSkepticism(v int32) {
	o.DispositionSkepticism = &v
}

// GetDispositionLiteralism returns the DispositionLiteralism field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetDispositionLiteralism() int32 {
	if o == nil || IsNil(o.DispositionLiteralism) {
		var ret int32
		return ret
	}
	return *o.DispositionLiteralism
}

// GetDispositionLiteralismOk returns a tuple with the DispositionLiteralism field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetDispositionLiteralismOk() (*int32, bool) {
	if o == nil || IsNil(o.DispositionLiteralism) {
		return nil, false
	}
	return o.DispositionLiteralism, true
}

// HasDispositionLiteralism returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasDispositionLiteralism() bool {
	if o != nil && !IsNil(o.DispositionLiteralism) {
		return true
	}

	return false
}

// SetDispositionLiteralism gets a reference to the given int32 and assigns it to the DispositionLiteralism field.
func (o *CreateTemplateRequest) SetDispositionLiteralism(v int32) {
	o.DispositionLiteralism = &v
}

// GetDispositionEmpathy returns the DispositionEmpathy field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetDispositionEmpathy() int32 {
	if o == nil || IsNil(o.DispositionEmpathy) {
		var ret int32
		return ret
	}
	return *o.DispositionEmpathy
}

// GetDispositionEmpathyOk returns a tuple with the DispositionEmpathy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetDispositionEmpathyOk() (*int32, bool) {
	if o == nil || IsNil(o.DispositionEmpathy) {
		return nil, false
	}
	return o.DispositionEmpathy, true
}

// HasDispositionEmpathy returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasDispositionEmpathy() bool {
	if o != nil && !IsNil(o.DispositionEmpathy) {
		return true
	}

	return false
}

// SetDispositionEmpathy gets a reference to the given int32 and assigns it to the DispositionEmpathy field.
func (o *CreateTemplateRequest) SetDispositionEmpathy(v int32) {
	o.DispositionEmpathy = &v
}

// GetDirectiveSeeds returns the DirectiveSeeds field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetDirectiveSeeds() []DirectiveSeed {
	if o == nil || IsNil(o.DirectiveSeeds) {
		var ret []DirectiveSeed
		return ret
	}
	return o.DirectiveSeeds
}

// GetDirectiveSeedsOk returns a tuple with the DirectiveSeeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetDirectiveSeedsOk() ([]DirectiveSeed, bool) {
	if o == nil || IsNil(o.DirectiveSeeds) {
		return nil, false
	}
	return o.DirectiveSeeds, true
}

// HasDirectiveSeeds returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasDirectiveSeeds() bool {
	if o != nil && !IsNil(o.DirectiveSeeds) {
		return true
	}

	return false
}

// SetDirectiveSeeds gets a reference to the given []DirectiveSeed and assigns it to the DirectiveSeeds field.
func (o *CreateTemplateRequest) SetDirectiveSeeds(v []DirectiveSeed) {
	o.DirectiveSeeds = v
}

// GetMentalModelSeeds returns the MentalModelSeeds field value if set, zero value otherwise.
func (o *CreateTemplateRequest) GetMentalModelSeeds() []MentalModelSeed {
	if o == nil || IsNil(o.MentalModelSeeds) {
		var ret []MentalModelSeed
		return ret
	}
	return o.MentalModelSeeds
}

// GetMentalModelSeedsOk returns a tuple with the MentalModelSeeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateRequest) GetMentalModelSeedsOk() ([]MentalModelSeed, bool) {
	if o == nil || IsNil(o.MentalModelSeeds) {
		return nil, false
	}
	return o.MentalModelSeeds, true
}

// HasMentalModelSeeds returns a boolean if a field has been set.
func (o *CreateTemplateRequest) HasMentalModelSeeds() bool {
	if o != nil && !IsNil(o.MentalModelSeeds) {
		return true
	}

	return false
}

// SetMentalModelSeeds gets a reference to the given []MentalModelSeed and assigns it to the MentalModelSeeds field.
func (o *CreateTemplateRequest) SetMentalModelSeeds(v []MentalModelSeed) {
	o.MentalModelSeeds = v
}

func (o CreateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["scope"] = o.Scope
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["min_hindclaw_version"] = o.MinHindclawVersion
	if o.MinHindsightVersion.IsSet() {
		toSerialize["min_hindsight_version"] = o.MinHindsightVersion.Get()
	}
	toSerialize["retain_mission"] = o.RetainMission
	toSerialize["reflect_mission"] = o.ReflectMission
	if o.ObservationsMission.IsSet() {
		toSerialize["observations_mission"] = o.ObservationsMission.Get()
	}
	if !IsNil(o.RetainExtractionMode) {
		toSerialize["retain_extraction_mode"] = o.RetainExtractionMode
	}
	if o.RetainCustomInstructions.IsSet() {
		toSerialize["retain_custom_instructions"] = o.RetainCustomInstructions.Get()
	}
	if !IsNil(o.RetainChunkSize) {
		toSerialize["retain_chunk_size"] = o.RetainChunkSize
	}
	if o.RetainDefaultStrategy.IsSet() {
		toSerialize["retain_default_strategy"] = o.RetainDefaultStrategy.Get()
	}
	if !IsNil(o.RetainStrategies) {
		toSerialize["retain_strategies"] = o.RetainStrategies
	}
	if !IsNil(o.EntityLabels) {
		toSerialize["entity_labels"] = o.EntityLabels
	}
	if !IsNil(o.EntitiesAllowFreeForm) {
		toSerialize["entities_allow_free_form"] = o.EntitiesAllowFreeForm
	}
	if !IsNil(o.EnableObservations) {
		toSerialize["enable_observations"] = o.EnableObservations
	}
	if !IsNil(o.ConsolidationLlmBatchSize) {
		toSerialize["consolidation_llm_batch_size"] = o.ConsolidationLlmBatchSize
	}
	if o.ConsolidationSourceFactsMaxTokens.IsSet() {
		toSerialize["consolidation_source_facts_max_tokens"] = o.ConsolidationSourceFactsMaxTokens.Get()
	}
	if o.ConsolidationSourceFactsMaxTokensPerObservation.IsSet() {
		toSerialize["consolidation_source_facts_max_tokens_per_observation"] = o.ConsolidationSourceFactsMaxTokensPerObservation.Get()
	}
	if !IsNil(o.DispositionSkepticism) {
		toSerialize["disposition_skepticism"] = o.DispositionSkepticism
	}
	if !IsNil(o.DispositionLiteralism) {
		toSerialize["disposition_literalism"] = o.DispositionLiteralism
	}
	if !IsNil(o.DispositionEmpathy) {
		toSerialize["disposition_empathy"] = o.DispositionEmpathy
	}
	if !IsNil(o.DirectiveSeeds) {
		toSerialize["directive_seeds"] = o.DirectiveSeeds
	}
	if !IsNil(o.MentalModelSeeds) {
		toSerialize["mental_model_seeds"] = o.MentalModelSeeds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"scope",
		"min_hindclaw_version",
		"retain_mission",
		"reflect_mission",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTemplateRequest := _CreateTemplateRequest{}

	err = json.Unmarshal(data, &varCreateTemplateRequest)

	if err != nil {
		return err
	}

	*o = CreateTemplateRequest(varCreateTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "description")
		delete(additionalProperties, "author")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "min_hindclaw_version")
		delete(additionalProperties, "min_hindsight_version")
		delete(additionalProperties, "retain_mission")
		delete(additionalProperties, "reflect_mission")
		delete(additionalProperties, "observations_mission")
		delete(additionalProperties, "retain_extraction_mode")
		delete(additionalProperties, "retain_custom_instructions")
		delete(additionalProperties, "retain_chunk_size")
		delete(additionalProperties, "retain_default_strategy")
		delete(additionalProperties, "retain_strategies")
		delete(additionalProperties, "entity_labels")
		delete(additionalProperties, "entities_allow_free_form")
		delete(additionalProperties, "enable_observations")
		delete(additionalProperties, "consolidation_llm_batch_size")
		delete(additionalProperties, "consolidation_source_facts_max_tokens")
		delete(additionalProperties, "consolidation_source_facts_max_tokens_per_observation")
		delete(additionalProperties, "disposition_skepticism")
		delete(additionalProperties, "disposition_literalism")
		delete(additionalProperties, "disposition_empathy")
		delete(additionalProperties, "directive_seeds")
		delete(additionalProperties, "mental_model_seeds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateTemplateRequest struct {
	value *CreateTemplateRequest
	isSet bool
}

func (v NullableCreateTemplateRequest) Get() *CreateTemplateRequest {
	return v.value
}

func (v *NullableCreateTemplateRequest) Set(val *CreateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateRequest(val *CreateTemplateRequest) *NullableCreateTemplateRequest {
	return &NullableCreateTemplateRequest{value: val, isSet: true}
}

func (v NullableCreateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


