/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTemplateResponse{}

// UpdateTemplateResponse struct for UpdateTemplateResponse
type UpdateTemplateResponse struct {
	Updated bool `json:"updated"`
	PreviousRevision NullableString `json:"previous_revision"`
	NewRevision NullableString `json:"new_revision"`
	Template TemplateResponse `json:"template"`
}

type _UpdateTemplateResponse UpdateTemplateResponse

// NewUpdateTemplateResponse instantiates a new UpdateTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTemplateResponse(updated bool, previousRevision NullableString, newRevision NullableString, template TemplateResponse) *UpdateTemplateResponse {
	this := UpdateTemplateResponse{}
	this.Updated = updated
	this.PreviousRevision = previousRevision
	this.NewRevision = newRevision
	this.Template = template
	return &this
}

// NewUpdateTemplateResponseWithDefaults instantiates a new UpdateTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTemplateResponseWithDefaults() *UpdateTemplateResponse {
	this := UpdateTemplateResponse{}
	return &this
}

// GetUpdated returns the Updated field value
func (o *UpdateTemplateResponse) GetUpdated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateTemplateResponse) GetUpdatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateTemplateResponse) SetUpdated(v bool) {
	o.Updated = v
}

// GetPreviousRevision returns the PreviousRevision field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateTemplateResponse) GetPreviousRevision() string {
	if o == nil || o.PreviousRevision.Get() == nil {
		var ret string
		return ret
	}

	return *o.PreviousRevision.Get()
}

// GetPreviousRevisionOk returns a tuple with the PreviousRevision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateResponse) GetPreviousRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousRevision.Get(), o.PreviousRevision.IsSet()
}

// SetPreviousRevision sets field value
func (o *UpdateTemplateResponse) SetPreviousRevision(v string) {
	o.PreviousRevision.Set(&v)
}

// GetNewRevision returns the NewRevision field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateTemplateResponse) GetNewRevision() string {
	if o == nil || o.NewRevision.Get() == nil {
		var ret string
		return ret
	}

	return *o.NewRevision.Get()
}

// GetNewRevisionOk returns a tuple with the NewRevision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTemplateResponse) GetNewRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewRevision.Get(), o.NewRevision.IsSet()
}

// SetNewRevision sets field value
func (o *UpdateTemplateResponse) SetNewRevision(v string) {
	o.NewRevision.Set(&v)
}

// GetTemplate returns the Template field value
func (o *UpdateTemplateResponse) GetTemplate() TemplateResponse {
	if o == nil {
		var ret TemplateResponse
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *UpdateTemplateResponse) GetTemplateOk() (*TemplateResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *UpdateTemplateResponse) SetTemplate(v TemplateResponse) {
	o.Template = v
}

func (o UpdateTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["updated"] = o.Updated
	toSerialize["previous_revision"] = o.PreviousRevision.Get()
	toSerialize["new_revision"] = o.NewRevision.Get()
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *UpdateTemplateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"updated",
		"previous_revision",
		"new_revision",
		"template",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTemplateResponse := _UpdateTemplateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTemplateResponse)

	if err != nil {
		return err
	}

	*o = UpdateTemplateResponse(varUpdateTemplateResponse)

	return err
}

type NullableUpdateTemplateResponse struct {
	value *UpdateTemplateResponse
	isSet bool
}

func (v NullableUpdateTemplateResponse) Get() *UpdateTemplateResponse {
	return v.value
}

func (v *NullableUpdateTemplateResponse) Set(val *UpdateTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTemplateResponse(val *UpdateTemplateResponse) *NullableUpdateTemplateResponse {
	return &NullableUpdateTemplateResponse{value: val, isSet: true}
}

func (v NullableUpdateTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


