/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)


// DirectiveSeeds struct for DirectiveSeeds
type DirectiveSeeds struct {
	ArrayOfDirectiveSeed *[]DirectiveSeed
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *DirectiveSeeds) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ArrayOfDirectiveSeed
	err = json.Unmarshal(data, &dst.ArrayOfDirectiveSeed);
	if err == nil {
		jsonArrayOfDirectiveSeed, _ := json.Marshal(dst.ArrayOfDirectiveSeed)
		if string(jsonArrayOfDirectiveSeed) == "{}" { // empty struct
			dst.ArrayOfDirectiveSeed = nil
		} else {
			return nil // data stored in dst.ArrayOfDirectiveSeed, return on the first match
		}
	} else {
		dst.ArrayOfDirectiveSeed = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(DirectiveSeeds)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *DirectiveSeeds) MarshalJSON() ([]byte, error) {
	if src.ArrayOfDirectiveSeed != nil {
		return json.Marshal(&src.ArrayOfDirectiveSeed)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableDirectiveSeeds struct {
	value *DirectiveSeeds
	isSet bool
}

func (v NullableDirectiveSeeds) Get() *DirectiveSeeds {
	return v.value
}

func (v *NullableDirectiveSeeds) Set(val *DirectiveSeeds) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectiveSeeds) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectiveSeeds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectiveSeeds(val *DirectiveSeeds) *NullableDirectiveSeeds {
	return &NullableDirectiveSeeds{value: val, isSet: true}
}

func (v NullableDirectiveSeeds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectiveSeeds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


