/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SAKeyCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SAKeyCreateResponse{}

// SAKeyCreateResponse SA API key at creation time — full key shown once.
type SAKeyCreateResponse struct {
	Id string `json:"id"`
	ApiKey string `json:"api_key"`
	Description string `json:"description"`
}

type _SAKeyCreateResponse SAKeyCreateResponse

// NewSAKeyCreateResponse instantiates a new SAKeyCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSAKeyCreateResponse(id string, apiKey string, description string) *SAKeyCreateResponse {
	this := SAKeyCreateResponse{}
	this.Id = id
	this.ApiKey = apiKey
	this.Description = description
	return &this
}

// NewSAKeyCreateResponseWithDefaults instantiates a new SAKeyCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSAKeyCreateResponseWithDefaults() *SAKeyCreateResponse {
	this := SAKeyCreateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *SAKeyCreateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SAKeyCreateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SAKeyCreateResponse) SetId(v string) {
	o.Id = v
}

// GetApiKey returns the ApiKey field value
func (o *SAKeyCreateResponse) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *SAKeyCreateResponse) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *SAKeyCreateResponse) SetApiKey(v string) {
	o.ApiKey = v
}

// GetDescription returns the Description field value
func (o *SAKeyCreateResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SAKeyCreateResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SAKeyCreateResponse) SetDescription(v string) {
	o.Description = v
}

func (o SAKeyCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SAKeyCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["api_key"] = o.ApiKey
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *SAKeyCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"api_key",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSAKeyCreateResponse := _SAKeyCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSAKeyCreateResponse)

	if err != nil {
		return err
	}

	*o = SAKeyCreateResponse(varSAKeyCreateResponse)

	return err
}

type NullableSAKeyCreateResponse struct {
	value *SAKeyCreateResponse
	isSet bool
}

func (v NullableSAKeyCreateResponse) Get() *SAKeyCreateResponse {
	return v.value
}

func (v *NullableSAKeyCreateResponse) Set(val *SAKeyCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSAKeyCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSAKeyCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSAKeyCreateResponse(val *SAKeyCreateResponse) *NullableSAKeyCreateResponse {
	return &NullableSAKeyCreateResponse{value: val, isSet: true}
}

func (v NullableSAKeyCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSAKeyCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


