/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectiveSeed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectiveSeed{}

// DirectiveSeed A directive to create when bootstrapping a bank from a template.
type DirectiveSeed struct {
	Name string `json:"name"`
	Content string `json:"content"`
	Priority *int32 `json:"priority,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
}

type _DirectiveSeed DirectiveSeed

// NewDirectiveSeed instantiates a new DirectiveSeed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectiveSeed(name string, content string) *DirectiveSeed {
	this := DirectiveSeed{}
	this.Name = name
	this.Content = content
	var priority int32 = 0
	this.Priority = &priority
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// NewDirectiveSeedWithDefaults instantiates a new DirectiveSeed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectiveSeedWithDefaults() *DirectiveSeed {
	this := DirectiveSeed{}
	var priority int32 = 0
	this.Priority = &priority
	var isActive bool = true
	this.IsActive = &isActive
	return &this
}

// GetName returns the Name field value
func (o *DirectiveSeed) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DirectiveSeed) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DirectiveSeed) SetName(v string) {
	o.Name = v
}

// GetContent returns the Content field value
func (o *DirectiveSeed) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *DirectiveSeed) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *DirectiveSeed) SetContent(v string) {
	o.Content = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *DirectiveSeed) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectiveSeed) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *DirectiveSeed) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *DirectiveSeed) SetPriority(v int32) {
	o.Priority = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *DirectiveSeed) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectiveSeed) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *DirectiveSeed) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *DirectiveSeed) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o DirectiveSeed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectiveSeed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["content"] = o.Content
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	return toSerialize, nil
}

func (o *DirectiveSeed) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectiveSeed := _DirectiveSeed{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectiveSeed)

	if err != nil {
		return err
	}

	*o = DirectiveSeed(varDirectiveSeed)

	return err
}

type NullableDirectiveSeed struct {
	value *DirectiveSeed
	isSet bool
}

func (v NullableDirectiveSeed) Get() *DirectiveSeed {
	return v.value
}

func (v *NullableDirectiveSeed) Set(val *DirectiveSeed) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectiveSeed) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectiveSeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectiveSeed(val *DirectiveSeed) *NullableDirectiveSeed {
	return &NullableDirectiveSeed{value: val, isSet: true}
}

func (v NullableDirectiveSeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectiveSeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


