/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateBankFromTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBankFromTemplateRequest{}

// CreateBankFromTemplateRequest Request to create a bank from an installed template.
type CreateBankFromTemplateRequest struct {
	BankId string `json:"bank_id"`
	Template string `json:"template"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateBankFromTemplateRequest CreateBankFromTemplateRequest

// NewCreateBankFromTemplateRequest instantiates a new CreateBankFromTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBankFromTemplateRequest(bankId string, template string) *CreateBankFromTemplateRequest {
	this := CreateBankFromTemplateRequest{}
	this.BankId = bankId
	this.Template = template
	return &this
}

// NewCreateBankFromTemplateRequestWithDefaults instantiates a new CreateBankFromTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBankFromTemplateRequestWithDefaults() *CreateBankFromTemplateRequest {
	this := CreateBankFromTemplateRequest{}
	return &this
}

// GetBankId returns the BankId field value
func (o *CreateBankFromTemplateRequest) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *CreateBankFromTemplateRequest) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *CreateBankFromTemplateRequest) SetBankId(v string) {
	o.BankId = v
}

// GetTemplate returns the Template field value
func (o *CreateBankFromTemplateRequest) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *CreateBankFromTemplateRequest) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *CreateBankFromTemplateRequest) SetTemplate(v string) {
	o.Template = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateBankFromTemplateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBankFromTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateBankFromTemplateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateBankFromTemplateRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateBankFromTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBankFromTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["template"] = o.Template
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBankFromTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"template",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBankFromTemplateRequest := _CreateBankFromTemplateRequest{}

	err = json.Unmarshal(data, &varCreateBankFromTemplateRequest)

	if err != nil {
		return err
	}

	*o = CreateBankFromTemplateRequest(varCreateBankFromTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "template")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBankFromTemplateRequest struct {
	value *CreateBankFromTemplateRequest
	isSet bool
}

func (v NullableCreateBankFromTemplateRequest) Get() *CreateBankFromTemplateRequest {
	return v.value
}

func (v *NullableCreateBankFromTemplateRequest) Set(val *CreateBankFromTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBankFromTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBankFromTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBankFromTemplateRequest(val *CreateBankFromTemplateRequest) *NullableCreateBankFromTemplateRequest {
	return &NullableCreateBankFromTemplateRequest{value: val, isSet: true}
}

func (v NullableCreateBankFromTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBankFromTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


