/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateSummaryResponse{}

// TemplateSummaryResponse Summary of a template for list endpoints.
type TemplateSummaryResponse struct {
	Id string `json:"id"`
	Scope string `json:"scope"`
	SourceName NullableString `json:"source_name"`
	Version NullableString `json:"version"`
	Description string `json:"description"`
	Author string `json:"author"`
	Tags []string `json:"tags"`
	RetainExtractionMode string `json:"retain_extraction_mode"`
	DispositionSkepticism int32 `json:"disposition_skepticism"`
	DispositionLiteralism int32 `json:"disposition_literalism"`
	DispositionEmpathy int32 `json:"disposition_empathy"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type _TemplateSummaryResponse TemplateSummaryResponse

// NewTemplateSummaryResponse instantiates a new TemplateSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSummaryResponse(id string, scope string, sourceName NullableString, version NullableString, description string, author string, tags []string, retainExtractionMode string, dispositionSkepticism int32, dispositionLiteralism int32, dispositionEmpathy int32, createdAt string, updatedAt string) *TemplateSummaryResponse {
	this := TemplateSummaryResponse{}
	this.Id = id
	this.Scope = scope
	this.SourceName = sourceName
	this.Version = version
	this.Description = description
	this.Author = author
	this.Tags = tags
	this.RetainExtractionMode = retainExtractionMode
	this.DispositionSkepticism = dispositionSkepticism
	this.DispositionLiteralism = dispositionLiteralism
	this.DispositionEmpathy = dispositionEmpathy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewTemplateSummaryResponseWithDefaults instantiates a new TemplateSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSummaryResponseWithDefaults() *TemplateSummaryResponse {
	this := TemplateSummaryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *TemplateSummaryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemplateSummaryResponse) SetId(v string) {
	o.Id = v
}

// GetScope returns the Scope field value
func (o *TemplateSummaryResponse) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *TemplateSummaryResponse) SetScope(v string) {
	o.Scope = v
}

// GetSourceName returns the SourceName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateSummaryResponse) GetSourceName() string {
	if o == nil || o.SourceName.Get() == nil {
		var ret string
		return ret
	}

	return *o.SourceName.Get()
}

// GetSourceNameOk returns a tuple with the SourceName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateSummaryResponse) GetSourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceName.Get(), o.SourceName.IsSet()
}

// SetSourceName sets field value
func (o *TemplateSummaryResponse) SetSourceName(v string) {
	o.SourceName.Set(&v)
}

// GetVersion returns the Version field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateSummaryResponse) GetVersion() string {
	if o == nil || o.Version.Get() == nil {
		var ret string
		return ret
	}

	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateSummaryResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// SetVersion sets field value
func (o *TemplateSummaryResponse) SetVersion(v string) {
	o.Version.Set(&v)
}

// GetDescription returns the Description field value
func (o *TemplateSummaryResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TemplateSummaryResponse) SetDescription(v string) {
	o.Description = v
}

// GetAuthor returns the Author field value
func (o *TemplateSummaryResponse) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *TemplateSummaryResponse) SetAuthor(v string) {
	o.Author = v
}

// GetTags returns the Tags field value
func (o *TemplateSummaryResponse) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *TemplateSummaryResponse) SetTags(v []string) {
	o.Tags = v
}

// GetRetainExtractionMode returns the RetainExtractionMode field value
func (o *TemplateSummaryResponse) GetRetainExtractionMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetainExtractionMode
}

// GetRetainExtractionModeOk returns a tuple with the RetainExtractionMode field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetRetainExtractionModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetainExtractionMode, true
}

// SetRetainExtractionMode sets field value
func (o *TemplateSummaryResponse) SetRetainExtractionMode(v string) {
	o.RetainExtractionMode = v
}

// GetDispositionSkepticism returns the DispositionSkepticism field value
func (o *TemplateSummaryResponse) GetDispositionSkepticism() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DispositionSkepticism
}

// GetDispositionSkepticismOk returns a tuple with the DispositionSkepticism field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetDispositionSkepticismOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DispositionSkepticism, true
}

// SetDispositionSkepticism sets field value
func (o *TemplateSummaryResponse) SetDispositionSkepticism(v int32) {
	o.DispositionSkepticism = v
}

// GetDispositionLiteralism returns the DispositionLiteralism field value
func (o *TemplateSummaryResponse) GetDispositionLiteralism() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DispositionLiteralism
}

// GetDispositionLiteralismOk returns a tuple with the DispositionLiteralism field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetDispositionLiteralismOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DispositionLiteralism, true
}

// SetDispositionLiteralism sets field value
func (o *TemplateSummaryResponse) SetDispositionLiteralism(v int32) {
	o.DispositionLiteralism = v
}

// GetDispositionEmpathy returns the DispositionEmpathy field value
func (o *TemplateSummaryResponse) GetDispositionEmpathy() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DispositionEmpathy
}

// GetDispositionEmpathyOk returns a tuple with the DispositionEmpathy field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetDispositionEmpathyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DispositionEmpathy, true
}

// SetDispositionEmpathy sets field value
func (o *TemplateSummaryResponse) SetDispositionEmpathy(v int32) {
	o.DispositionEmpathy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TemplateSummaryResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TemplateSummaryResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TemplateSummaryResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TemplateSummaryResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o TemplateSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["scope"] = o.Scope
	toSerialize["source_name"] = o.SourceName.Get()
	toSerialize["version"] = o.Version.Get()
	toSerialize["description"] = o.Description
	toSerialize["author"] = o.Author
	toSerialize["tags"] = o.Tags
	toSerialize["retain_extraction_mode"] = o.RetainExtractionMode
	toSerialize["disposition_skepticism"] = o.DispositionSkepticism
	toSerialize["disposition_literalism"] = o.DispositionLiteralism
	toSerialize["disposition_empathy"] = o.DispositionEmpathy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *TemplateSummaryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"scope",
		"source_name",
		"version",
		"description",
		"author",
		"tags",
		"retain_extraction_mode",
		"disposition_skepticism",
		"disposition_literalism",
		"disposition_empathy",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateSummaryResponse := _TemplateSummaryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateSummaryResponse)

	if err != nil {
		return err
	}

	*o = TemplateSummaryResponse(varTemplateSummaryResponse)

	return err
}

type NullableTemplateSummaryResponse struct {
	value *TemplateSummaryResponse
	isSet bool
}

func (v NullableTemplateSummaryResponse) Get() *TemplateSummaryResponse {
	return v.value
}

func (v *NullableTemplateSummaryResponse) Set(val *TemplateSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSummaryResponse(val *TemplateSummaryResponse) *NullableTemplateSummaryResponse {
	return &NullableTemplateSummaryResponse{value: val, isSet: true}
}

func (v NullableTemplateSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


