/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// checks if the InstallTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallTemplateRequest{}

// InstallTemplateRequest Request to install a template from a marketplace source.
type InstallTemplateRequest struct {
	// Marketplace source name
	Source string `json:"source"`
	// Template name within the source
	Name string `json:"name"`
	// 'server' or 'personal'
	Scope string `json:"scope"`
	AdditionalProperties map[string]interface{}
}

type _InstallTemplateRequest InstallTemplateRequest

// NewInstallTemplateRequest instantiates a new InstallTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallTemplateRequest(source string, name string, scope string) *InstallTemplateRequest {
	this := InstallTemplateRequest{}
	this.Source = source
	this.Name = name
	this.Scope = scope
	return &this
}

// NewInstallTemplateRequestWithDefaults instantiates a new InstallTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallTemplateRequestWithDefaults() *InstallTemplateRequest {
	this := InstallTemplateRequest{}
	return &this
}

// GetSource returns the Source field value
func (o *InstallTemplateRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *InstallTemplateRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *InstallTemplateRequest) SetSource(v string) {
	o.Source = v
}

// GetName returns the Name field value
func (o *InstallTemplateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InstallTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InstallTemplateRequest) SetName(v string) {
	o.Name = v
}

// GetScope returns the Scope field value
func (o *InstallTemplateRequest) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *InstallTemplateRequest) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *InstallTemplateRequest) SetScope(v string) {
	o.Scope = v
}

func (o InstallTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["name"] = o.Name
	toSerialize["scope"] = o.Scope

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InstallTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"name",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstallTemplateRequest := _InstallTemplateRequest{}

	err = json.Unmarshal(data, &varInstallTemplateRequest)

	if err != nil {
		return err
	}

	*o = InstallTemplateRequest(varInstallTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "name")
		delete(additionalProperties, "scope")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInstallTemplateRequest struct {
	value *InstallTemplateRequest
	isSet bool
}

func (v NullableInstallTemplateRequest) Get() *InstallTemplateRequest {
	return v.value
}

func (v *NullableInstallTemplateRequest) Set(val *InstallTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallTemplateRequest(val *InstallTemplateRequest) *NullableInstallTemplateRequest {
	return &NullableInstallTemplateRequest{value: val, isSet: true}
}

func (v NullableInstallTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


