/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)


// MinHindclawVersion struct for MinHindclawVersion
type MinHindclawVersion struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *MinHindclawVersion) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(MinHindclawVersion)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *MinHindclawVersion) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableMinHindclawVersion struct {
	value *MinHindclawVersion
	isSet bool
}

func (v NullableMinHindclawVersion) Get() *MinHindclawVersion {
	return v.value
}

func (v *NullableMinHindclawVersion) Set(val *MinHindclawVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableMinHindclawVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableMinHindclawVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinHindclawVersion(val *MinHindclawVersion) *NullableMinHindclawVersion {
	return &NullableMinHindclawVersion{value: val, isSet: true}
}

func (v NullableMinHindclawVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinHindclawVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


