/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)


// EntityLabels struct for EntityLabels
type EntityLabels struct {
	ArrayOfEntityLabel *[]EntityLabel
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EntityLabels) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ArrayOfEntityLabel
	err = json.Unmarshal(data, &dst.ArrayOfEntityLabel);
	if err == nil {
		jsonArrayOfEntityLabel, _ := json.Marshal(dst.ArrayOfEntityLabel)
		if string(jsonArrayOfEntityLabel) == "{}" { // empty struct
			dst.ArrayOfEntityLabel = nil
		} else {
			return nil // data stored in dst.ArrayOfEntityLabel, return on the first match
		}
	} else {
		dst.ArrayOfEntityLabel = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(EntityLabels)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *EntityLabels) MarshalJSON() ([]byte, error) {
	if src.ArrayOfEntityLabel != nil {
		return json.Marshal(&src.ArrayOfEntityLabel)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableEntityLabels struct {
	value *EntityLabels
	isSet bool
}

func (v NullableEntityLabels) Get() *EntityLabels {
	return v.value
}

func (v *NullableEntityLabels) Set(val *EntityLabels) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityLabels(val *EntityLabels) *NullableEntityLabels {
	return &NullableEntityLabels{value: val, isSet: true}
}

func (v NullableEntityLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


