/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// checks if the InstallTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallTemplateRequest{}

// InstallTemplateRequest Request to install a template from a marketplace source.  The ``{id}`` in the URL path is the template id WITHIN the source. The installed-template id is ``alias_id`` if provided, else the source template id. This lets a user install the same source template under a different installed name (Section 4.3 identity invariant: at most one row per (id, scope, owner)).
type InstallTemplateRequest struct {
	SourceName string `json:"source_name"`
	SourceScope *TemplateScope `json:"source_scope,omitempty"`
	AliasId NullableString `json:"alias_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InstallTemplateRequest InstallTemplateRequest

// NewInstallTemplateRequest instantiates a new InstallTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallTemplateRequest(sourceName string) *InstallTemplateRequest {
	this := InstallTemplateRequest{}
	this.SourceName = sourceName
	return &this
}

// NewInstallTemplateRequestWithDefaults instantiates a new InstallTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallTemplateRequestWithDefaults() *InstallTemplateRequest {
	this := InstallTemplateRequest{}
	return &this
}

// GetSourceName returns the SourceName field value
func (o *InstallTemplateRequest) GetSourceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value
// and a boolean to check if the value has been set.
func (o *InstallTemplateRequest) GetSourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceName, true
}

// SetSourceName sets field value
func (o *InstallTemplateRequest) SetSourceName(v string) {
	o.SourceName = v
}

// GetSourceScope returns the SourceScope field value if set, zero value otherwise.
func (o *InstallTemplateRequest) GetSourceScope() TemplateScope {
	if o == nil || IsNil(o.SourceScope) {
		var ret TemplateScope
		return ret
	}
	return *o.SourceScope
}

// GetSourceScopeOk returns a tuple with the SourceScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallTemplateRequest) GetSourceScopeOk() (*TemplateScope, bool) {
	if o == nil || IsNil(o.SourceScope) {
		return nil, false
	}
	return o.SourceScope, true
}

// HasSourceScope returns a boolean if a field has been set.
func (o *InstallTemplateRequest) HasSourceScope() bool {
	if o != nil && !IsNil(o.SourceScope) {
		return true
	}

	return false
}

// SetSourceScope gets a reference to the given TemplateScope and assigns it to the SourceScope field.
func (o *InstallTemplateRequest) SetSourceScope(v TemplateScope) {
	o.SourceScope = &v
}

// GetAliasId returns the AliasId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstallTemplateRequest) GetAliasId() string {
	if o == nil || IsNil(o.AliasId.Get()) {
		var ret string
		return ret
	}
	return *o.AliasId.Get()
}

// GetAliasIdOk returns a tuple with the AliasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstallTemplateRequest) GetAliasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AliasId.Get(), o.AliasId.IsSet()
}

// HasAliasId returns a boolean if a field has been set.
func (o *InstallTemplateRequest) HasAliasId() bool {
	if o != nil && o.AliasId.IsSet() {
		return true
	}

	return false
}

// SetAliasId gets a reference to the given NullableString and assigns it to the AliasId field.
func (o *InstallTemplateRequest) SetAliasId(v string) {
	o.AliasId.Set(&v)
}
// SetAliasIdNil sets the value for AliasId to be an explicit nil
func (o *InstallTemplateRequest) SetAliasIdNil() {
	o.AliasId.Set(nil)
}

// UnsetAliasId ensures that no value is present for AliasId, not even an explicit nil
func (o *InstallTemplateRequest) UnsetAliasId() {
	o.AliasId.Unset()
}

func (o InstallTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_name"] = o.SourceName
	if !IsNil(o.SourceScope) {
		toSerialize["source_scope"] = o.SourceScope
	}
	if o.AliasId.IsSet() {
		toSerialize["alias_id"] = o.AliasId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InstallTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstallTemplateRequest := _InstallTemplateRequest{}

	err = json.Unmarshal(data, &varInstallTemplateRequest)

	if err != nil {
		return err
	}

	*o = InstallTemplateRequest(varInstallTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source_name")
		delete(additionalProperties, "source_scope")
		delete(additionalProperties, "alias_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInstallTemplateRequest struct {
	value *InstallTemplateRequest
	isSet bool
}

func (v NullableInstallTemplateRequest) Get() *InstallTemplateRequest {
	return v.value
}

func (v *NullableInstallTemplateRequest) Set(val *InstallTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallTemplateRequest(val *InstallTemplateRequest) *NullableInstallTemplateRequest {
	return &NullableInstallTemplateRequest{value: val, isSet: true}
}

func (v NullableInstallTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


