/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)


// EntitiesAllowFreeForm struct for EntitiesAllowFreeForm
type EntitiesAllowFreeForm struct {
	Bool *bool
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EntitiesAllowFreeForm) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Bool
	err = json.Unmarshal(data, &dst.Bool);
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			return nil // data stored in dst.Bool, return on the first match
		}
	} else {
		dst.Bool = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(EntitiesAllowFreeForm)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *EntitiesAllowFreeForm) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableEntitiesAllowFreeForm struct {
	value *EntitiesAllowFreeForm
	isSet bool
}

func (v NullableEntitiesAllowFreeForm) Get() *EntitiesAllowFreeForm {
	return v.value
}

func (v *NullableEntitiesAllowFreeForm) Set(val *EntitiesAllowFreeForm) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitiesAllowFreeForm) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitiesAllowFreeForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitiesAllowFreeForm(val *EntitiesAllowFreeForm) *NullableEntitiesAllowFreeForm {
	return &NullableEntitiesAllowFreeForm{value: val, isSet: true}
}

func (v NullableEntitiesAllowFreeForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitiesAllowFreeForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


