/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SAKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SAKeyResponse{}

// SAKeyResponse SA API key in list view — key is masked.
type SAKeyResponse struct {
	Id string `json:"id"`
	ApiKeyPrefix string `json:"api_key_prefix"`
	Description string `json:"description"`
}

type _SAKeyResponse SAKeyResponse

// NewSAKeyResponse instantiates a new SAKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSAKeyResponse(id string, apiKeyPrefix string, description string) *SAKeyResponse {
	this := SAKeyResponse{}
	this.Id = id
	this.ApiKeyPrefix = apiKeyPrefix
	this.Description = description
	return &this
}

// NewSAKeyResponseWithDefaults instantiates a new SAKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSAKeyResponseWithDefaults() *SAKeyResponse {
	this := SAKeyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *SAKeyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SAKeyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SAKeyResponse) SetId(v string) {
	o.Id = v
}

// GetApiKeyPrefix returns the ApiKeyPrefix field value
func (o *SAKeyResponse) GetApiKeyPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKeyPrefix
}

// GetApiKeyPrefixOk returns a tuple with the ApiKeyPrefix field value
// and a boolean to check if the value has been set.
func (o *SAKeyResponse) GetApiKeyPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKeyPrefix, true
}

// SetApiKeyPrefix sets field value
func (o *SAKeyResponse) SetApiKeyPrefix(v string) {
	o.ApiKeyPrefix = v
}

// GetDescription returns the Description field value
func (o *SAKeyResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SAKeyResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SAKeyResponse) SetDescription(v string) {
	o.Description = v
}

func (o SAKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SAKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["api_key_prefix"] = o.ApiKeyPrefix
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *SAKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"api_key_prefix",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSAKeyResponse := _SAKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSAKeyResponse)

	if err != nil {
		return err
	}

	*o = SAKeyResponse(varSAKeyResponse)

	return err
}

type NullableSAKeyResponse struct {
	value *SAKeyResponse
	isSet bool
}

func (v NullableSAKeyResponse) Get() *SAKeyResponse {
	return v.value
}

func (v *NullableSAKeyResponse) Set(val *SAKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSAKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSAKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSAKeyResponse(val *SAKeyResponse) *NullableSAKeyResponse {
	return &NullableSAKeyResponse{value: val, isSet: true}
}

func (v NullableSAKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSAKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


