/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyResponse{}

// PolicyResponse Access policy resource.
type PolicyResponse struct {
	Id string `json:"id"`
	DisplayName string `json:"display_name"`
	Document map[string]interface{} `json:"document"`
	IsBuiltin bool `json:"is_builtin"`
}

type _PolicyResponse PolicyResponse

// NewPolicyResponse instantiates a new PolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyResponse(id string, displayName string, document map[string]interface{}, isBuiltin bool) *PolicyResponse {
	this := PolicyResponse{}
	this.Id = id
	this.DisplayName = displayName
	this.Document = document
	this.IsBuiltin = isBuiltin
	return &this
}

// NewPolicyResponseWithDefaults instantiates a new PolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyResponseWithDefaults() *PolicyResponse {
	this := PolicyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *PolicyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PolicyResponse) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *PolicyResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *PolicyResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDocument returns the Document field value
func (o *PolicyResponse) GetDocument() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// SetDocument sets field value
func (o *PolicyResponse) SetDocument(v map[string]interface{}) {
	o.Document = v
}

// GetIsBuiltin returns the IsBuiltin field value
func (o *PolicyResponse) GetIsBuiltin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBuiltin
}

// GetIsBuiltinOk returns a tuple with the IsBuiltin field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetIsBuiltinOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBuiltin, true
}

// SetIsBuiltin sets field value
func (o *PolicyResponse) SetIsBuiltin(v bool) {
	o.IsBuiltin = v
}

func (o PolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	toSerialize["document"] = o.Document
	toSerialize["is_builtin"] = o.IsBuiltin
	return toSerialize, nil
}

func (o *PolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
		"document",
		"is_builtin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyResponse := _PolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyResponse)

	if err != nil {
		return err
	}

	*o = PolicyResponse(varPolicyResponse)

	return err
}

type NullablePolicyResponse struct {
	value *PolicyResponse
	isSet bool
}

func (v NullablePolicyResponse) Get() *PolicyResponse {
	return v.value
}

func (v *NullablePolicyResponse) Set(val *PolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyResponse(val *PolicyResponse) *NullablePolicyResponse {
	return &NullablePolicyResponse{value: val, isSet: true}
}

func (v NullablePolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


