/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankCreationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankCreationResponse{}

// BankCreationResponse Response from POST /ext/hindclaw/banks — bank creation from template.
type BankCreationResponse struct {
	BankId string `json:"bank_id"`
	Template string `json:"template"`
	BankCreated bool `json:"bank_created"`
	ConfigApplied bool `json:"config_applied"`
	Directives []DirectiveSeedResult `json:"directives"`
	MentalModels []MentalModelSeedResult `json:"mental_models"`
	Errors []string `json:"errors"`
}

type _BankCreationResponse BankCreationResponse

// NewBankCreationResponse instantiates a new BankCreationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankCreationResponse(bankId string, template string, bankCreated bool, configApplied bool, directives []DirectiveSeedResult, mentalModels []MentalModelSeedResult, errors []string) *BankCreationResponse {
	this := BankCreationResponse{}
	this.BankId = bankId
	this.Template = template
	this.BankCreated = bankCreated
	this.ConfigApplied = configApplied
	this.Directives = directives
	this.MentalModels = mentalModels
	this.Errors = errors
	return &this
}

// NewBankCreationResponseWithDefaults instantiates a new BankCreationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankCreationResponseWithDefaults() *BankCreationResponse {
	this := BankCreationResponse{}
	return &this
}

// GetBankId returns the BankId field value
func (o *BankCreationResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *BankCreationResponse) SetBankId(v string) {
	o.BankId = v
}

// GetTemplate returns the Template field value
func (o *BankCreationResponse) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *BankCreationResponse) SetTemplate(v string) {
	o.Template = v
}

// GetBankCreated returns the BankCreated field value
func (o *BankCreationResponse) GetBankCreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BankCreated
}

// GetBankCreatedOk returns a tuple with the BankCreated field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetBankCreatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankCreated, true
}

// SetBankCreated sets field value
func (o *BankCreationResponse) SetBankCreated(v bool) {
	o.BankCreated = v
}

// GetConfigApplied returns the ConfigApplied field value
func (o *BankCreationResponse) GetConfigApplied() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConfigApplied
}

// GetConfigAppliedOk returns a tuple with the ConfigApplied field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetConfigAppliedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigApplied, true
}

// SetConfigApplied sets field value
func (o *BankCreationResponse) SetConfigApplied(v bool) {
	o.ConfigApplied = v
}

// GetDirectives returns the Directives field value
func (o *BankCreationResponse) GetDirectives() []DirectiveSeedResult {
	if o == nil {
		var ret []DirectiveSeedResult
		return ret
	}

	return o.Directives
}

// GetDirectivesOk returns a tuple with the Directives field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetDirectivesOk() ([]DirectiveSeedResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Directives, true
}

// SetDirectives sets field value
func (o *BankCreationResponse) SetDirectives(v []DirectiveSeedResult) {
	o.Directives = v
}

// GetMentalModels returns the MentalModels field value
func (o *BankCreationResponse) GetMentalModels() []MentalModelSeedResult {
	if o == nil {
		var ret []MentalModelSeedResult
		return ret
	}

	return o.MentalModels
}

// GetMentalModelsOk returns a tuple with the MentalModels field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetMentalModelsOk() ([]MentalModelSeedResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.MentalModels, true
}

// SetMentalModels sets field value
func (o *BankCreationResponse) SetMentalModels(v []MentalModelSeedResult) {
	o.MentalModels = v
}

// GetErrors returns the Errors field value
func (o *BankCreationResponse) GetErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *BankCreationResponse) GetErrorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *BankCreationResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o BankCreationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankCreationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["template"] = o.Template
	toSerialize["bank_created"] = o.BankCreated
	toSerialize["config_applied"] = o.ConfigApplied
	toSerialize["directives"] = o.Directives
	toSerialize["mental_models"] = o.MentalModels
	toSerialize["errors"] = o.Errors
	return toSerialize, nil
}

func (o *BankCreationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"template",
		"bank_created",
		"config_applied",
		"directives",
		"mental_models",
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankCreationResponse := _BankCreationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankCreationResponse)

	if err != nil {
		return err
	}

	*o = BankCreationResponse(varBankCreationResponse)

	return err
}

type NullableBankCreationResponse struct {
	value *BankCreationResponse
	isSet bool
}

func (v NullableBankCreationResponse) Get() *BankCreationResponse {
	return v.value
}

func (v *NullableBankCreationResponse) Set(val *BankCreationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBankCreationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBankCreationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankCreationResponse(val *BankCreationResponse) *NullableBankCreationResponse {
	return &NullableBankCreationResponse{value: val, isSet: true}
}

func (v NullableBankCreationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankCreationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


