/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityLabel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityLabel{}

// EntityLabel An entity label definition for structured classification.  Hindsight supports three label types: - \"value\": single enum value from the values list - \"multi-values\": multiple enum values from the values list - \"text\": free-form text (no values list needed)  The ``tag`` field controls whether facts with this label also get tagged (enabling tag-based filtering in recall/reflect).
type EntityLabel struct {
	Key string `json:"key"`
	Description *string `json:"description,omitempty"`
	Type *string `json:"type,omitempty"`
	Optional *bool `json:"optional,omitempty"`
	Tag *bool `json:"tag,omitempty"`
	Values []EntityLabelValue `json:"values,omitempty"`
}

type _EntityLabel EntityLabel

// NewEntityLabel instantiates a new EntityLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityLabel(key string) *EntityLabel {
	this := EntityLabel{}
	this.Key = key
	var description string = ""
	this.Description = &description
	var type_ string = "value"
	this.Type = &type_
	var optional bool = true
	this.Optional = &optional
	var tag bool = false
	this.Tag = &tag
	return &this
}

// NewEntityLabelWithDefaults instantiates a new EntityLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityLabelWithDefaults() *EntityLabel {
	this := EntityLabel{}
	var description string = ""
	this.Description = &description
	var type_ string = "value"
	this.Type = &type_
	var optional bool = true
	this.Optional = &optional
	var tag bool = false
	this.Tag = &tag
	return &this
}

// GetKey returns the Key field value
func (o *EntityLabel) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *EntityLabel) SetKey(v string) {
	o.Key = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EntityLabel) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EntityLabel) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EntityLabel) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntityLabel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntityLabel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EntityLabel) SetType(v string) {
	o.Type = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *EntityLabel) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *EntityLabel) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *EntityLabel) SetOptional(v bool) {
	o.Optional = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *EntityLabel) GetTag() bool {
	if o == nil || IsNil(o.Tag) {
		var ret bool
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetTagOk() (*bool, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *EntityLabel) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given bool and assigns it to the Tag field.
func (o *EntityLabel) SetTag(v bool) {
	o.Tag = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *EntityLabel) GetValues() []EntityLabelValue {
	if o == nil || IsNil(o.Values) {
		var ret []EntityLabelValue
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityLabel) GetValuesOk() ([]EntityLabelValue, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *EntityLabel) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []EntityLabelValue and assigns it to the Values field.
func (o *EntityLabel) SetValues(v []EntityLabelValue) {
	o.Values = v
}

func (o EntityLabel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityLabel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

func (o *EntityLabel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityLabel := _EntityLabel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityLabel)

	if err != nil {
		return err
	}

	*o = EntityLabel(varEntityLabel)

	return err
}

type NullableEntityLabel struct {
	value *EntityLabel
	isSet bool
}

func (v NullableEntityLabel) Get() *EntityLabel {
	return v.value
}

func (v *NullableEntityLabel) Set(val *EntityLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityLabel(val *EntityLabel) *NullableEntityLabel {
	return &NullableEntityLabel{value: val, isSet: true}
}

func (v NullableEntityLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


