/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
)

// checks if the UpdateServiceAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateServiceAccountRequest{}

// UpdateServiceAccountRequest Request to update a service account.
type UpdateServiceAccountRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	ScopingPolicyId *string `json:"scoping_policy_id,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
}

// NewUpdateServiceAccountRequest instantiates a new UpdateServiceAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateServiceAccountRequest() *UpdateServiceAccountRequest {
	this := UpdateServiceAccountRequest{}
	return &this
}

// NewUpdateServiceAccountRequestWithDefaults instantiates a new UpdateServiceAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateServiceAccountRequestWithDefaults() *UpdateServiceAccountRequest {
	this := UpdateServiceAccountRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateServiceAccountRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServiceAccountRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateServiceAccountRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateServiceAccountRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetScopingPolicyId returns the ScopingPolicyId field value if set, zero value otherwise.
func (o *UpdateServiceAccountRequest) GetScopingPolicyId() string {
	if o == nil || IsNil(o.ScopingPolicyId) {
		var ret string
		return ret
	}
	return *o.ScopingPolicyId
}

// GetScopingPolicyIdOk returns a tuple with the ScopingPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServiceAccountRequest) GetScopingPolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScopingPolicyId) {
		return nil, false
	}
	return o.ScopingPolicyId, true
}

// HasScopingPolicyId returns a boolean if a field has been set.
func (o *UpdateServiceAccountRequest) HasScopingPolicyId() bool {
	if o != nil && !IsNil(o.ScopingPolicyId) {
		return true
	}

	return false
}

// SetScopingPolicyId gets a reference to the given string and assigns it to the ScopingPolicyId field.
func (o *UpdateServiceAccountRequest) SetScopingPolicyId(v string) {
	o.ScopingPolicyId = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *UpdateServiceAccountRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServiceAccountRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *UpdateServiceAccountRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *UpdateServiceAccountRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o UpdateServiceAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateServiceAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.ScopingPolicyId) {
		toSerialize["scoping_policy_id"] = o.ScopingPolicyId
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableUpdateServiceAccountRequest struct {
	value *UpdateServiceAccountRequest
	isSet bool
}

func (v NullableUpdateServiceAccountRequest) Get() *UpdateServiceAccountRequest {
	return v.value
}

func (v *NullableUpdateServiceAccountRequest) Set(val *UpdateServiceAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateServiceAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateServiceAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateServiceAccountRequest(val *UpdateServiceAccountRequest) *NullableUpdateServiceAccountRequest {
	return &NullableUpdateServiceAccountRequest{value: val, isSet: true}
}

func (v NullableUpdateServiceAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateServiceAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


