/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateUpdateResponse{}

// TemplateUpdateResponse Response for template update from marketplace.
type TemplateUpdateResponse struct {
	Updated bool `json:"updated"`
	PreviousVersion string `json:"previous_version"`
	NewVersion string `json:"new_version"`
	Template *TemplateResponse `json:"template,omitempty"`
}

type _TemplateUpdateResponse TemplateUpdateResponse

// NewTemplateUpdateResponse instantiates a new TemplateUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateUpdateResponse(updated bool, previousVersion string, newVersion string) *TemplateUpdateResponse {
	this := TemplateUpdateResponse{}
	this.Updated = updated
	this.PreviousVersion = previousVersion
	this.NewVersion = newVersion
	return &this
}

// NewTemplateUpdateResponseWithDefaults instantiates a new TemplateUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateUpdateResponseWithDefaults() *TemplateUpdateResponse {
	this := TemplateUpdateResponse{}
	return &this
}

// GetUpdated returns the Updated field value
func (o *TemplateUpdateResponse) GetUpdated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *TemplateUpdateResponse) GetUpdatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *TemplateUpdateResponse) SetUpdated(v bool) {
	o.Updated = v
}

// GetPreviousVersion returns the PreviousVersion field value
func (o *TemplateUpdateResponse) GetPreviousVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviousVersion
}

// GetPreviousVersionOk returns a tuple with the PreviousVersion field value
// and a boolean to check if the value has been set.
func (o *TemplateUpdateResponse) GetPreviousVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousVersion, true
}

// SetPreviousVersion sets field value
func (o *TemplateUpdateResponse) SetPreviousVersion(v string) {
	o.PreviousVersion = v
}

// GetNewVersion returns the NewVersion field value
func (o *TemplateUpdateResponse) GetNewVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewVersion
}

// GetNewVersionOk returns a tuple with the NewVersion field value
// and a boolean to check if the value has been set.
func (o *TemplateUpdateResponse) GetNewVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewVersion, true
}

// SetNewVersion sets field value
func (o *TemplateUpdateResponse) SetNewVersion(v string) {
	o.NewVersion = v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *TemplateUpdateResponse) GetTemplate() TemplateResponse {
	if o == nil || IsNil(o.Template) {
		var ret TemplateResponse
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateUpdateResponse) GetTemplateOk() (*TemplateResponse, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *TemplateUpdateResponse) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given TemplateResponse and assigns it to the Template field.
func (o *TemplateUpdateResponse) SetTemplate(v TemplateResponse) {
	o.Template = &v
}

func (o TemplateUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["updated"] = o.Updated
	toSerialize["previous_version"] = o.PreviousVersion
	toSerialize["new_version"] = o.NewVersion
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	return toSerialize, nil
}

func (o *TemplateUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"updated",
		"previous_version",
		"new_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateUpdateResponse := _TemplateUpdateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateUpdateResponse)

	if err != nil {
		return err
	}

	*o = TemplateUpdateResponse(varTemplateUpdateResponse)

	return err
}

type NullableTemplateUpdateResponse struct {
	value *TemplateUpdateResponse
	isSet bool
}

func (v NullableTemplateUpdateResponse) Get() *TemplateUpdateResponse {
	return v.value
}

func (v *NullableTemplateUpdateResponse) Set(val *TemplateUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateUpdateResponse(val *TemplateUpdateResponse) *NullableTemplateUpdateResponse {
	return &NullableTemplateUpdateResponse{value: val, isSet: true}
}

func (v NullableTemplateUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


