/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSourceRequest{}

// CreateSourceRequest Request to register a marketplace source.
type CreateSourceRequest struct {
	// Marketplace repository URL
	Url string `json:"url"`
	Alias NullableString `json:"alias,omitempty"`
	AuthToken NullableString `json:"auth_token,omitempty"`
	Description NullableString `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSourceRequest CreateSourceRequest

// NewCreateSourceRequest instantiates a new CreateSourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSourceRequest(url string) *CreateSourceRequest {
	this := CreateSourceRequest{}
	this.Url = url
	return &this
}

// NewCreateSourceRequestWithDefaults instantiates a new CreateSourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSourceRequestWithDefaults() *CreateSourceRequest {
	this := CreateSourceRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *CreateSourceRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateSourceRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateSourceRequest) SetUrl(v string) {
	o.Url = v
}

// GetAlias returns the Alias field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSourceRequest) GetAlias() string {
	if o == nil || IsNil(o.Alias.Get()) {
		var ret string
		return ret
	}
	return *o.Alias.Get()
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSourceRequest) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alias.Get(), o.Alias.IsSet()
}

// HasAlias returns a boolean if a field has been set.
func (o *CreateSourceRequest) HasAlias() bool {
	if o != nil && o.Alias.IsSet() {
		return true
	}

	return false
}

// SetAlias gets a reference to the given NullableString and assigns it to the Alias field.
func (o *CreateSourceRequest) SetAlias(v string) {
	o.Alias.Set(&v)
}
// SetAliasNil sets the value for Alias to be an explicit nil
func (o *CreateSourceRequest) SetAliasNil() {
	o.Alias.Set(nil)
}

// UnsetAlias ensures that no value is present for Alias, not even an explicit nil
func (o *CreateSourceRequest) UnsetAlias() {
	o.Alias.Unset()
}

// GetAuthToken returns the AuthToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSourceRequest) GetAuthToken() string {
	if o == nil || IsNil(o.AuthToken.Get()) {
		var ret string
		return ret
	}
	return *o.AuthToken.Get()
}

// GetAuthTokenOk returns a tuple with the AuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSourceRequest) GetAuthTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthToken.Get(), o.AuthToken.IsSet()
}

// HasAuthToken returns a boolean if a field has been set.
func (o *CreateSourceRequest) HasAuthToken() bool {
	if o != nil && o.AuthToken.IsSet() {
		return true
	}

	return false
}

// SetAuthToken gets a reference to the given NullableString and assigns it to the AuthToken field.
func (o *CreateSourceRequest) SetAuthToken(v string) {
	o.AuthToken.Set(&v)
}
// SetAuthTokenNil sets the value for AuthToken to be an explicit nil
func (o *CreateSourceRequest) SetAuthTokenNil() {
	o.AuthToken.Set(nil)
}

// UnsetAuthToken ensures that no value is present for AuthToken, not even an explicit nil
func (o *CreateSourceRequest) UnsetAuthToken() {
	o.AuthToken.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSourceRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSourceRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSourceRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateSourceRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateSourceRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateSourceRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o CreateSourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if o.Alias.IsSet() {
		toSerialize["alias"] = o.Alias.Get()
	}
	if o.AuthToken.IsSet() {
		toSerialize["auth_token"] = o.AuthToken.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSourceRequest := _CreateSourceRequest{}

	err = json.Unmarshal(data, &varCreateSourceRequest)

	if err != nil {
		return err
	}

	*o = CreateSourceRequest(varCreateSourceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "alias")
		delete(additionalProperties, "auth_token")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSourceRequest struct {
	value *CreateSourceRequest
	isSet bool
}

func (v NullableCreateSourceRequest) Get() *CreateSourceRequest {
	return v.value
}

func (v *NullableCreateSourceRequest) Set(val *CreateSourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSourceRequest(val *CreateSourceRequest) *NullableCreateSourceRequest {
	return &NullableCreateSourceRequest{value: val, isSet: true}
}

func (v NullableCreateSourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


