/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)


// RetainMission struct for RetainMission
type RetainMission struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RetainMission) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RetainMission)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *RetainMission) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRetainMission struct {
	value *RetainMission
	isSet bool
}

func (v NullableRetainMission) Get() *RetainMission {
	return v.value
}

func (v *NullableRetainMission) Set(val *RetainMission) {
	v.value = val
	v.isSet = true
}

func (v NullableRetainMission) IsSet() bool {
	return v.isSet
}

func (v *NullableRetainMission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetainMission(val *RetainMission) *NullableRetainMission {
	return &NullableRetainMission{value: val, isSet: true}
}

func (v NullableRetainMission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetainMission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


