# coding: utf-8

"""
    Hindclaw API

    Access control API for Hindsight memory server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hindclaw_client_api.models.template_scope import TemplateScope
from typing import Optional, Set
from typing_extensions import Self

class CheckUpdateResponse(BaseModel):
    """
    CheckUpdateResponse
    """ # noqa: E501
    has_update: StrictBool
    current_revision: Optional[StrictStr]
    latest_revision: Optional[StrictStr]
    source_name: Optional[StrictStr] = None
    source_scope: Optional[TemplateScope] = None
    __properties: ClassVar[List[str]] = ["has_update", "current_revision", "latest_revision", "source_name", "source_scope"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckUpdateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if current_revision (nullable) is None
        # and model_fields_set contains the field
        if self.current_revision is None and "current_revision" in self.model_fields_set:
            _dict['current_revision'] = None

        # set to None if latest_revision (nullable) is None
        # and model_fields_set contains the field
        if self.latest_revision is None and "latest_revision" in self.model_fields_set:
            _dict['latest_revision'] = None

        # set to None if source_name (nullable) is None
        # and model_fields_set contains the field
        if self.source_name is None and "source_name" in self.model_fields_set:
            _dict['source_name'] = None

        # set to None if source_scope (nullable) is None
        # and model_fields_set contains the field
        if self.source_scope is None and "source_scope" in self.model_fields_set:
            _dict['source_scope'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckUpdateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "has_update": obj.get("has_update"),
            "current_revision": obj.get("current_revision"),
            "latest_revision": obj.get("latest_revision"),
            "source_name": obj.get("source_name"),
            "source_scope": obj.get("source_scope")
        })
        return _obj


