# coding: utf-8

"""
    Hindclaw API

    Access control API for Hindsight memory server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class TemplateSummaryResponse(BaseModel):
    """
    Summary of a template for list endpoints.
    """ # noqa: E501
    id: StrictStr
    scope: StrictStr
    source_name: StrictStr
    version: StrictStr
    description: StrictStr
    author: StrictStr
    tags: List[StrictStr]
    retain_extraction_mode: StrictStr
    disposition_skepticism: StrictInt
    disposition_literalism: StrictInt
    disposition_empathy: StrictInt
    created_at: StrictStr
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["id", "scope", "source_name", "version", "description", "author", "tags", "retain_extraction_mode", "disposition_skepticism", "disposition_literalism", "disposition_empathy", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateSummaryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateSummaryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "scope": obj.get("scope"),
            "source_name": obj.get("source_name"),
            "version": obj.get("version"),
            "description": obj.get("description"),
            "author": obj.get("author"),
            "tags": obj.get("tags"),
            "retain_extraction_mode": obj.get("retain_extraction_mode"),
            "disposition_skepticism": obj.get("disposition_skepticism"),
            "disposition_literalism": obj.get("disposition_literalism"),
            "disposition_empathy": obj.get("disposition_empathy"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


