# coding: utf-8

"""
    Hindclaw API

    Access control API for Hindsight memory server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class TemplateResponse(BaseModel):
    """
    Full template details.
    """ # noqa: E501
    id: StrictStr
    scope: StrictStr
    owner: StrictStr
    source_name: StrictStr
    schema_version: StrictInt
    min_hindclaw_version: StrictStr
    min_hindsight_version: StrictStr
    version: StrictStr
    source_url: StrictStr
    source_revision: StrictStr
    description: StrictStr
    author: StrictStr
    tags: List[StrictStr]
    retain_mission: StrictStr
    reflect_mission: StrictStr
    observations_mission: StrictStr
    retain_extraction_mode: StrictStr
    retain_custom_instructions: StrictStr
    retain_chunk_size: StrictInt
    retain_default_strategy: StrictStr
    retain_strategies: Dict[str, Any]
    entity_labels: List[Dict[str, Any]]
    entities_allow_free_form: StrictBool
    enable_observations: StrictBool
    consolidation_llm_batch_size: StrictInt
    consolidation_source_facts_max_tokens: StrictInt
    consolidation_source_facts_max_tokens_per_observation: StrictInt
    disposition_skepticism: StrictInt
    disposition_literalism: StrictInt
    disposition_empathy: StrictInt
    directive_seeds: List[Dict[str, Any]]
    mental_model_seeds: List[Dict[str, Any]]
    created_at: StrictStr
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["id", "scope", "owner", "source_name", "schema_version", "min_hindclaw_version", "min_hindsight_version", "version", "source_url", "source_revision", "description", "author", "tags", "retain_mission", "reflect_mission", "observations_mission", "retain_extraction_mode", "retain_custom_instructions", "retain_chunk_size", "retain_default_strategy", "retain_strategies", "entity_labels", "entities_allow_free_form", "enable_observations", "consolidation_llm_batch_size", "consolidation_source_facts_max_tokens", "consolidation_source_facts_max_tokens_per_observation", "disposition_skepticism", "disposition_literalism", "disposition_empathy", "directive_seeds", "mental_model_seeds", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "scope": obj.get("scope"),
            "owner": obj.get("owner"),
            "source_name": obj.get("source_name"),
            "schema_version": obj.get("schema_version"),
            "min_hindclaw_version": obj.get("min_hindclaw_version"),
            "min_hindsight_version": obj.get("min_hindsight_version"),
            "version": obj.get("version"),
            "source_url": obj.get("source_url"),
            "source_revision": obj.get("source_revision"),
            "description": obj.get("description"),
            "author": obj.get("author"),
            "tags": obj.get("tags"),
            "retain_mission": obj.get("retain_mission"),
            "reflect_mission": obj.get("reflect_mission"),
            "observations_mission": obj.get("observations_mission"),
            "retain_extraction_mode": obj.get("retain_extraction_mode"),
            "retain_custom_instructions": obj.get("retain_custom_instructions"),
            "retain_chunk_size": obj.get("retain_chunk_size"),
            "retain_default_strategy": obj.get("retain_default_strategy"),
            "retain_strategies": obj.get("retain_strategies"),
            "entity_labels": obj.get("entity_labels"),
            "entities_allow_free_form": obj.get("entities_allow_free_form"),
            "enable_observations": obj.get("enable_observations"),
            "consolidation_llm_batch_size": obj.get("consolidation_llm_batch_size"),
            "consolidation_source_facts_max_tokens": obj.get("consolidation_source_facts_max_tokens"),
            "consolidation_source_facts_max_tokens_per_observation": obj.get("consolidation_source_facts_max_tokens_per_observation"),
            "disposition_skepticism": obj.get("disposition_skepticism"),
            "disposition_literalism": obj.get("disposition_literalism"),
            "disposition_empathy": obj.get("disposition_empathy"),
            "directive_seeds": obj.get("directive_seeds"),
            "mental_model_seeds": obj.get("mental_model_seeds"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


