/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"fmt"
)

// TemplateScope Template visibility scope.
type TemplateScope string

// List of TemplateScope
const (
	TEMPLATESCOPE_SERVER TemplateScope = "server"
	TEMPLATESCOPE_PERSONAL TemplateScope = "personal"
)

// All allowed values of TemplateScope enum
var AllowedTemplateScopeEnumValues = []TemplateScope{
	"server",
	"personal",
}

func (v *TemplateScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TemplateScope(value)
	for _, existing := range AllowedTemplateScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TemplateScope", value)
}

// NewTemplateScopeFromValue returns a pointer to a valid TemplateScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTemplateScopeFromValue(v string) (*TemplateScope, error) {
	ev := TemplateScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TemplateScope: valid values are %v", v, AllowedTemplateScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TemplateScope) IsValid() bool {
	for _, existing := range AllowedTemplateScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TemplateScope value
func (v TemplateScope) Ptr() *TemplateScope {
	return &v
}

type NullableTemplateScope struct {
	value *TemplateScope
	isSet bool
}

func (v NullableTemplateScope) Get() *TemplateScope {
	return v.value
}

func (v *NullableTemplateScope) Set(val *TemplateScope) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateScope) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateScope(val *TemplateScope) *NullableTemplateScope {
	return &NullableTemplateScope{value: val, isSet: true}
}

func (v NullableTemplateScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

