/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListTemplatesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTemplatesResponse{}

// ListTemplatesResponse struct for ListTemplatesResponse
type ListTemplatesResponse struct {
	Templates []TemplateResponse `json:"templates"`
}

type _ListTemplatesResponse ListTemplatesResponse

// NewListTemplatesResponse instantiates a new ListTemplatesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTemplatesResponse(templates []TemplateResponse) *ListTemplatesResponse {
	this := ListTemplatesResponse{}
	this.Templates = templates
	return &this
}

// NewListTemplatesResponseWithDefaults instantiates a new ListTemplatesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTemplatesResponseWithDefaults() *ListTemplatesResponse {
	this := ListTemplatesResponse{}
	return &this
}

// GetTemplates returns the Templates field value
func (o *ListTemplatesResponse) GetTemplates() []TemplateResponse {
	if o == nil {
		var ret []TemplateResponse
		return ret
	}

	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value
// and a boolean to check if the value has been set.
func (o *ListTemplatesResponse) GetTemplatesOk() ([]TemplateResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Templates, true
}

// SetTemplates sets field value
func (o *ListTemplatesResponse) SetTemplates(v []TemplateResponse) {
	o.Templates = v
}

func (o ListTemplatesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTemplatesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templates"] = o.Templates
	return toSerialize, nil
}

func (o *ListTemplatesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"templates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTemplatesResponse := _ListTemplatesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListTemplatesResponse)

	if err != nil {
		return err
	}

	*o = ListTemplatesResponse(varListTemplatesResponse)

	return err
}

type NullableListTemplatesResponse struct {
	value *ListTemplatesResponse
	isSet bool
}

func (v NullableListTemplatesResponse) Get() *ListTemplatesResponse {
	return v.value
}

func (v *NullableListTemplatesResponse) Set(val *ListTemplatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTemplatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTemplatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTemplatesResponse(val *ListTemplatesResponse) *NullableListTemplatesResponse {
	return &NullableListTemplatesResponse{value: val, isSet: true}
}

func (v NullableListTemplatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTemplatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


