/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeProfileResponse{}

// MeProfileResponse Response for GET /me — caller's own profile.
type MeProfileResponse struct {
	Id string `json:"id"`
	DisplayName string `json:"display_name"`
	Email NullableString `json:"email"`
	IsActive bool `json:"is_active"`
	Channels []ChannelResponse `json:"channels"`
}

type _MeProfileResponse MeProfileResponse

// NewMeProfileResponse instantiates a new MeProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeProfileResponse(id string, displayName string, email NullableString, isActive bool, channels []ChannelResponse) *MeProfileResponse {
	this := MeProfileResponse{}
	this.Id = id
	this.DisplayName = displayName
	this.Email = email
	this.IsActive = isActive
	this.Channels = channels
	return &this
}

// NewMeProfileResponseWithDefaults instantiates a new MeProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeProfileResponseWithDefaults() *MeProfileResponse {
	this := MeProfileResponse{}
	return &this
}

// GetId returns the Id field value
func (o *MeProfileResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MeProfileResponse) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *MeProfileResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *MeProfileResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetEmail returns the Email field value
// If the value is explicit nil, the zero value for string will be returned
func (o *MeProfileResponse) GetEmail() string {
	if o == nil || o.Email.Get() == nil {
		var ret string
		return ret
	}

	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// SetEmail sets field value
func (o *MeProfileResponse) SetEmail(v string) {
	o.Email.Set(&v)
}

// GetIsActive returns the IsActive field value
func (o *MeProfileResponse) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *MeProfileResponse) SetIsActive(v bool) {
	o.IsActive = v
}

// GetChannels returns the Channels field value
func (o *MeProfileResponse) GetChannels() []ChannelResponse {
	if o == nil {
		var ret []ChannelResponse
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetChannelsOk() ([]ChannelResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *MeProfileResponse) SetChannels(v []ChannelResponse) {
	o.Channels = v
}

func (o MeProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	toSerialize["email"] = o.Email.Get()
	toSerialize["is_active"] = o.IsActive
	toSerialize["channels"] = o.Channels
	return toSerialize, nil
}

func (o *MeProfileResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
		"email",
		"is_active",
		"channels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeProfileResponse := _MeProfileResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeProfileResponse)

	if err != nil {
		return err
	}

	*o = MeProfileResponse(varMeProfileResponse)

	return err
}

type NullableMeProfileResponse struct {
	value *MeProfileResponse
	isSet bool
}

func (v NullableMeProfileResponse) Get() *MeProfileResponse {
	return v.value
}

func (v *NullableMeProfileResponse) Set(val *MeProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMeProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMeProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeProfileResponse(val *MeProfileResponse) *NullableMeProfileResponse {
	return &NullableMeProfileResponse{value: val, isSet: true}
}

func (v NullableMeProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


