/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankPolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankPolicyResponse{}

// BankPolicyResponse Bank policy resource.
type BankPolicyResponse struct {
	BankId string `json:"bank_id"`
	Document map[string]interface{} `json:"document"`
}

type _BankPolicyResponse BankPolicyResponse

// NewBankPolicyResponse instantiates a new BankPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankPolicyResponse(bankId string, document map[string]interface{}) *BankPolicyResponse {
	this := BankPolicyResponse{}
	this.BankId = bankId
	this.Document = document
	return &this
}

// NewBankPolicyResponseWithDefaults instantiates a new BankPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankPolicyResponseWithDefaults() *BankPolicyResponse {
	this := BankPolicyResponse{}
	return &this
}

// GetBankId returns the BankId field value
func (o *BankPolicyResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *BankPolicyResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *BankPolicyResponse) SetBankId(v string) {
	o.BankId = v
}

// GetDocument returns the Document field value
func (o *BankPolicyResponse) GetDocument() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value
// and a boolean to check if the value has been set.
func (o *BankPolicyResponse) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// SetDocument sets field value
func (o *BankPolicyResponse) SetDocument(v map[string]interface{}) {
	o.Document = v
}

func (o BankPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankPolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["document"] = o.Document
	return toSerialize, nil
}

func (o *BankPolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"document",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankPolicyResponse := _BankPolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankPolicyResponse)

	if err != nil {
		return err
	}

	*o = BankPolicyResponse(varBankPolicyResponse)

	return err
}

type NullableBankPolicyResponse struct {
	value *BankPolicyResponse
	isSet bool
}

func (v NullableBankPolicyResponse) Get() *BankPolicyResponse {
	return v.value
}

func (v *NullableBankPolicyResponse) Set(val *BankPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBankPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBankPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankPolicyResponse(val *BankPolicyResponse) *NullableBankPolicyResponse {
	return &NullableBankPolicyResponse{value: val, isSet: true}
}

func (v NullableBankPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


