/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
)

// checks if the UpdatePolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePolicyRequest{}

// UpdatePolicyRequest Request to update an access policy.
type UpdatePolicyRequest struct {
	DisplayName NullableString `json:"display_name,omitempty"`
	Document map[string]interface{} `json:"document,omitempty"`
}

// NewUpdatePolicyRequest instantiates a new UpdatePolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePolicyRequest() *UpdatePolicyRequest {
	this := UpdatePolicyRequest{}
	return &this
}

// NewUpdatePolicyRequestWithDefaults instantiates a new UpdatePolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePolicyRequestWithDefaults() *UpdatePolicyRequest {
	this := UpdatePolicyRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePolicyRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePolicyRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdatePolicyRequest) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *UpdatePolicyRequest) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *UpdatePolicyRequest) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *UpdatePolicyRequest) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetDocument returns the Document field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePolicyRequest) GetDocument() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePolicyRequest) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Document) {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// HasDocument returns a boolean if a field has been set.
func (o *UpdatePolicyRequest) HasDocument() bool {
	if o != nil && !IsNil(o.Document) {
		return true
	}

	return false
}

// SetDocument gets a reference to the given map[string]interface{} and assigns it to the Document field.
func (o *UpdatePolicyRequest) SetDocument(v map[string]interface{}) {
	o.Document = v
}

func (o UpdatePolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DisplayName.IsSet() {
		toSerialize["display_name"] = o.DisplayName.Get()
	}
	if o.Document != nil {
		toSerialize["document"] = o.Document
	}
	return toSerialize, nil
}

type NullableUpdatePolicyRequest struct {
	value *UpdatePolicyRequest
	isSet bool
}

func (v NullableUpdatePolicyRequest) Get() *UpdatePolicyRequest {
	return v.value
}

func (v *NullableUpdatePolicyRequest) Set(val *UpdatePolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePolicyRequest(val *UpdatePolicyRequest) *NullableUpdatePolicyRequest {
	return &NullableUpdatePolicyRequest{value: val, isSet: true}
}

func (v NullableUpdatePolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


