/*
Hindclaw API

Access control API for Hindsight memory server

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindclaw

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponse{}

// TemplateResponse Installed template, surfaced over the API.
type TemplateResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description NullableString `json:"description"`
	Category NullableString `json:"category"`
	Integrations []string `json:"integrations"`
	Tags []string `json:"tags"`
	Scope TemplateScope `json:"scope"`
	Owner NullableString `json:"owner"`
	SourceName NullableString `json:"source_name"`
	SourceScope NullableTemplateScope `json:"source_scope"`
	SourceOwner NullableString `json:"source_owner"`
	SourceRevision NullableString `json:"source_revision"`
	InstalledAt time.Time `json:"installed_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Manifest map[string]interface{} `json:"manifest"`
}

type _TemplateResponse TemplateResponse

// NewTemplateResponse instantiates a new TemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponse(id string, name string, description NullableString, category NullableString, integrations []string, tags []string, scope TemplateScope, owner NullableString, sourceName NullableString, sourceScope NullableTemplateScope, sourceOwner NullableString, sourceRevision NullableString, installedAt time.Time, updatedAt time.Time, manifest map[string]interface{}) *TemplateResponse {
	this := TemplateResponse{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Category = category
	this.Integrations = integrations
	this.Tags = tags
	this.Scope = scope
	this.Owner = owner
	this.SourceName = sourceName
	this.SourceScope = sourceScope
	this.SourceOwner = sourceOwner
	this.SourceRevision = sourceRevision
	this.InstalledAt = installedAt
	this.UpdatedAt = updatedAt
	this.Manifest = manifest
	return &this
}

// NewTemplateResponseWithDefaults instantiates a new TemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseWithDefaults() *TemplateResponse {
	this := TemplateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *TemplateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemplateResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TemplateResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *TemplateResponse) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetCategory returns the Category field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetCategory() string {
	if o == nil || o.Category.Get() == nil {
		var ret string
		return ret
	}

	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// SetCategory sets field value
func (o *TemplateResponse) SetCategory(v string) {
	o.Category.Set(&v)
}

// GetIntegrations returns the Integrations field value
func (o *TemplateResponse) GetIntegrations() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Integrations
}

// GetIntegrationsOk returns a tuple with the Integrations field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetIntegrationsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Integrations, true
}

// SetIntegrations sets field value
func (o *TemplateResponse) SetIntegrations(v []string) {
	o.Integrations = v
}

// GetTags returns the Tags field value
func (o *TemplateResponse) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *TemplateResponse) SetTags(v []string) {
	o.Tags = v
}

// GetScope returns the Scope field value
func (o *TemplateResponse) GetScope() TemplateScope {
	if o == nil {
		var ret TemplateScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetScopeOk() (*TemplateScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *TemplateResponse) SetScope(v TemplateScope) {
	o.Scope = v
}

// GetOwner returns the Owner field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetOwner() string {
	if o == nil || o.Owner.Get() == nil {
		var ret string
		return ret
	}

	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// SetOwner sets field value
func (o *TemplateResponse) SetOwner(v string) {
	o.Owner.Set(&v)
}

// GetSourceName returns the SourceName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetSourceName() string {
	if o == nil || o.SourceName.Get() == nil {
		var ret string
		return ret
	}

	return *o.SourceName.Get()
}

// GetSourceNameOk returns a tuple with the SourceName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetSourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceName.Get(), o.SourceName.IsSet()
}

// SetSourceName sets field value
func (o *TemplateResponse) SetSourceName(v string) {
	o.SourceName.Set(&v)
}

// GetSourceScope returns the SourceScope field value
// If the value is explicit nil, the zero value for TemplateScope will be returned
func (o *TemplateResponse) GetSourceScope() TemplateScope {
	if o == nil || o.SourceScope.Get() == nil {
		var ret TemplateScope
		return ret
	}

	return *o.SourceScope.Get()
}

// GetSourceScopeOk returns a tuple with the SourceScope field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetSourceScopeOk() (*TemplateScope, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceScope.Get(), o.SourceScope.IsSet()
}

// SetSourceScope sets field value
func (o *TemplateResponse) SetSourceScope(v TemplateScope) {
	o.SourceScope.Set(&v)
}

// GetSourceOwner returns the SourceOwner field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetSourceOwner() string {
	if o == nil || o.SourceOwner.Get() == nil {
		var ret string
		return ret
	}

	return *o.SourceOwner.Get()
}

// GetSourceOwnerOk returns a tuple with the SourceOwner field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetSourceOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceOwner.Get(), o.SourceOwner.IsSet()
}

// SetSourceOwner sets field value
func (o *TemplateResponse) SetSourceOwner(v string) {
	o.SourceOwner.Set(&v)
}

// GetSourceRevision returns the SourceRevision field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TemplateResponse) GetSourceRevision() string {
	if o == nil || o.SourceRevision.Get() == nil {
		var ret string
		return ret
	}

	return *o.SourceRevision.Get()
}

// GetSourceRevisionOk returns a tuple with the SourceRevision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponse) GetSourceRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceRevision.Get(), o.SourceRevision.IsSet()
}

// SetSourceRevision sets field value
func (o *TemplateResponse) SetSourceRevision(v string) {
	o.SourceRevision.Set(&v)
}

// GetInstalledAt returns the InstalledAt field value
func (o *TemplateResponse) GetInstalledAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.InstalledAt
}

// GetInstalledAtOk returns a tuple with the InstalledAt field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetInstalledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstalledAt, true
}

// SetInstalledAt sets field value
func (o *TemplateResponse) SetInstalledAt(v time.Time) {
	o.InstalledAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TemplateResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TemplateResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetManifest returns the Manifest field value
func (o *TemplateResponse) GetManifest() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Manifest
}

// GetManifestOk returns a tuple with the Manifest field value
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetManifestOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Manifest, true
}

// SetManifest sets field value
func (o *TemplateResponse) SetManifest(v map[string]interface{}) {
	o.Manifest = v
}

func (o TemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["category"] = o.Category.Get()
	toSerialize["integrations"] = o.Integrations
	toSerialize["tags"] = o.Tags
	toSerialize["scope"] = o.Scope
	toSerialize["owner"] = o.Owner.Get()
	toSerialize["source_name"] = o.SourceName.Get()
	toSerialize["source_scope"] = o.SourceScope.Get()
	toSerialize["source_owner"] = o.SourceOwner.Get()
	toSerialize["source_revision"] = o.SourceRevision.Get()
	toSerialize["installed_at"] = o.InstalledAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["manifest"] = o.Manifest
	return toSerialize, nil
}

func (o *TemplateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"category",
		"integrations",
		"tags",
		"scope",
		"owner",
		"source_name",
		"source_scope",
		"source_owner",
		"source_revision",
		"installed_at",
		"updated_at",
		"manifest",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateResponse := _TemplateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateResponse)

	if err != nil {
		return err
	}

	*o = TemplateResponse(varTemplateResponse)

	return err
}

type NullableTemplateResponse struct {
	value *TemplateResponse
	isSet bool
}

func (v NullableTemplateResponse) Get() *TemplateResponse {
	return v.value
}

func (v *NullableTemplateResponse) Set(val *TemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponse(val *TemplateResponse) *NullableTemplateResponse {
	return &NullableTemplateResponse{value: val, isSet: true}
}

func (v NullableTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


